// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_AturanPakai")]
[Index("IdAturanpakai", Name = "IX_L_AturanPakai_IdAturanPakai")]
[Index("IsAktif", Name = "IX_L_AturanPakai_IsAktif")]
[Index("KdAturanPakai", Name = "IX_L_AturanPakai_KdAturanPakai")]
[Index("KetAturanpakai", Name = "IX_L_AturanPakai_KetAturanPakai")]
[Index("NamaAturanpakai", Name = "IX_L_AturanPakai_NmAturanPakai")]
public partial class L_Aturanpakai
{
    [Key]
    [Column("IdAturanpakai", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdAturanpakai { get; set; }

    [Column("KdAturanPakai")]
    [StringLength(10)]
    [Unicode(false)]
    public string KdAturanPakai { get; set; }

    [Column("NamaAturanpakai")]
    [StringLength(50)]
    [Unicode(false)]
    public string NamaAturanpakai { get; set; }

    [Column("KetAturanpakai")]
    [StringLength(50)]
    [Unicode(false)]
    public string KetAturanpakai { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }
}