// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_DiagnosaMatrix")]
public partial class L_DiagnosaMatrix
{
    [Key]
    [Column("IdMatrixDiagnosa", TypeName = "decimal(18, 2)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdDiagnosaMatrix { get; set; }


    [Column("IdRuangan")]
    public decimal IdRuangan { get; set; }

    [Column("KodeRuangan")]
    [StringLength(8)]
    [Unicode(false)]
    public string Koderuangan { get; set; }

    [Column("IdDiagnosa", TypeName = "decimal(18,2)")]
    public decimal IdDiagnosa { get; set; }

    [Column("KdDiagnosa")]
    [StringLength(8)]
    [Unicode(false)]
    public string Kddiagnosa { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }
}