// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_DokterHonor")]
public partial class L_DokterHonor
{
    [Key]
    [Column("Id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal Id { get; set; }

    [Column("KdDokter")]
    [StringLength(6)]
    [Unicode(false)]
    [Required]
    public string KdDokter { get; set; }

    [Column("NmDokter")]
    [StringLength(100)]
    [Unicode(false)]
    public string NmDokter { get; set; }

    [Column("Tarif", TypeName = "decimal(18, 0)")]
    public decimal? Tarif { get; set; }

    [Column("JasaMedis", TypeName = "decimal(18, 0)")]
    public decimal? JasaMedis { get; set; }

    [Column("JasaRS", TypeName = "decimal(18, 0)")]
    public decimal? JasaRS { get; set; }

    [Column("Ket")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ket { get; set; }
}