// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("L_DTD")]
public partial class L_Dtd
{
    [Key]
    [Column("IdDTD", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdDtd { get; set; }

    [Column("KdDTD")]
    [StringLength(8)]
    [Unicode(false)]
    [Required]
    public string Kddtd { get; set; }

    [Column("NmDTD")]
    [StringLength(200)]
    [Unicode(false)]
    public string Nmdtd { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }
}