// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("L_FarmakoterapiSub")]
public partial class L_FarmakoterapiSub
{
    [Key]
    [Column("IdSubFarmakoterapi", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdSubfarmakoterapi { get; set; }

    [Column("NmSubFarmakoterapi")]
    [StringLength(200)]
    [Unicode(false)]
    public string NmSubFarmakoterapi { get; set; }

    [Column("IdFarmakoterapi", TypeName = "numeric(18, 0)")]
    public decimal? IdFarmakoterapi { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }

    [ForeignKey("IdFarmakoterapi")]
    [InverseProperty("L_FarmakoterapiSubs")]
    public virtual L_Farmakoterapi IdFarmakoterapiNavigation { get; set; }

   // [InverseProperty("IdSubfarmakoterapiNavigation")]
   // public virtual ICollection<L_Barang> LBarangs { get; set; } = new List<L_Barang>();
}