// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_Morfologi")]
public partial class L_Morfologi
{
    [Key]
    [Column("IdMorfologi", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdMorfologi { get; set; }

    [Column("KdMorfologi")]
    [StringLength(8)]
    [Unicode(false)]
    public string Kdmorfologi { get; set; }

    [Column("NmMorfologi")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nmmorfologi { get; set; }

    [Column("KdDiagnosa")]
    [StringLength(8)]
    [Unicode(false)]
    public string Kddiagnosa { get; set; }

    [Column("IdDiagnosa", TypeName = "decimal(18,0)")]
    public decimal IdDiagnosa { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }

    [ForeignKey("IdDiagnosa")]
    [InverseProperty("L_Morfologis")]
    public virtual L_Diagnosa KdDiagnosaNavigation { get; set; }
}