// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("L_PaketMatrix")]
public partial class L_PaketMatrix
{
    [Key]
    [Column("IdPaketMatrix")]
    public Guid IdPaketmatrix { get; set; }

    [Column("OldIdPaketmatrix", TypeName = "numeric(18, 0)")]
    public decimal OldIdPaketmatrix { get; set; }

    [Column("IdMasterpemeriksaanpenunjang", TypeName = "numeric(18, 0)")]
    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    [Column("Koderuangan")]
    [StringLength(5)]
    [Unicode(false)]
    public string KodeRuangan { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }
}