// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_RItemPaket")]
public partial class L_RItemPaket
{
    [Key]
    [Column("IdDetailPaket", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid IdDetailpaket { get; set; }
    
    [Column("OldIdDetailPaket", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid IdDetailpaket { get; set; }

    [Column("IdPaket", TypeName = "numeric(18, 0)")]
    public decimal? IdPaket { get; set; }

    [Column("VNomorPaket")]
    [StringLength(12)]
    [Unicode(false)]
    public string VNomorpaket { get; set; }

    [Column("IdMasterPemeriksaanPenunjang", TypeName = "numeric(18, 0)")]
    public decimal? IdMasterpemeriksaanpenunjang { get; set; }

    [Column("IdPenunjangDetail", TypeName = "numeric(18, 0)")]
    public decimal? IdPenunjangdetail { get; set; }

    [Column("VKodeDetail")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKddetail { get; set; }

    [Column("VNmDetail")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmdetail { get; set; }

    [Column("VGroup")]
    [StringLength(100)]
    [Unicode(false)]
    public string VGroup { get; set; }

    [Column("VTipe")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTipe { get; set; }

    [Column("VKdDokter")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("VNmDokter")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNmdokter { get; set; }

    [Column("DJumlah", TypeName = "decimal(18, 0)")]
    public decimal? DJumlah { get; set; }

    [Column("DHarga", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("DCito", TypeName = "decimal(18, 0)")]
    public decimal? DCito { get; set; }

    [Column("DPenyulit", TypeName = "decimal(18, 0)")]
    public decimal? DPenyulit { get; set; }

    [Column("D2tnd", TypeName = "decimal(18, 0)")]
    public decimal? D2tnd { get; set; }

    [Column("DAdm", TypeName = "decimal(18, 0)")]
    public decimal? DAdm { get; set; }

    [Column("DDiskon", TypeName = "decimal(18, 0)")]
    public decimal? DDiskon { get; set; }

    [Column("DSubtotal", TypeName = "decimal(18, 0)")]
    public decimal? DSubtotal { get; set; }

    [Column("DBeaPasien", TypeName = "decimal(18, 0)")]
    public decimal? DBeapasien { get; set; }

    [Column("DBeaRekanan", TypeName = "decimal(18, 0)")]
    public decimal? DBearekanan { get; set; }

    [Column("DJasaMedis", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis { get; set; }

    [Column("DJasaMedis2", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis2 { get; set; }

    [Column("DJasaMedis3", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis3 { get; set; }

    [Column("DJasaMedis4", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis4 { get; set; }

    [Column("DJasaMedis5", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis5 { get; set; }

    [Column("DJasars", TypeName = "decimal(18, 0)")]
    public decimal? DJasars { get; set; }

    [Column("DBahanalkes", TypeName = "decimal(18, 0)")]
    public decimal? DBahanalkes { get; set; }

    [Column("VKodeTarif")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKodetarif { get; set; }

    [Column("VBy")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("CApprove")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("DApprove", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("VApproveVer")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [Column("CApproveVer")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("DApproveVer", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [Column("IdStatus")]
    public int? IdStatus { get; set; }

    [ForeignKey("IdPaket")]
    [InverseProperty("L_RItempakets")]
    public virtual L_TPaket IdPaketNavigation { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("L_RItempakets")]
    public virtual L_Status IdStatusNavigation { get; set; }
}