// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("L_RJadwalDokter")]
public partial class L_RJadwaldokter
{
    [Key]
    [Column("IdJadwal")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long IdJadwal { get; set; }

    [Column("VKdDokter")]
    [StringLength(100)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("VHari")]
    [StringLength(30)]
    [Unicode(false)]
    public string VHari { get; set; }

    [Column("VJamStart")]
    [StringLength(5)]
    [Unicode(false)]
    public string VJamstart { get; set; }

    [Column("VJamFinish")]
    [StringLength(5)]
    [Unicode(false)]
    public string VJamfinish { get; set; }

    [Column("VKodeRuangan")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKoderuangan { get; set; }

    [Column("VNamaKlinik")]
    [StringLength(5)]
    [Unicode(false)]
    public string VNamaklinik { get; set; }

    [Column("IServisTime")]
    public int? IServistime { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }

    [Column("VBy")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }
}