// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_Status")]
[Index("Status", Name = "IX_L_Status")]
[Index("IdStatus", Name = "IX_L_Status_1")]
public partial class L_Status
{
     [Key]
    [Column("IdStatus")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdStatus { get; set; }

    [Column("VStatus")]
    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }
}