// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_Standartfield")]
public partial class L_Standartfield
{
    [Key]
    [Column("IdField", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdField { get; set; }

    [Column("IdFieldgroup", TypeName = "numeric(18, 0)")]
    public decimal? IdFieldgroup { get; set; }

    [Column("KodeField")]
    [StringLength(5)]
    [Unicode(false)]
    [Required]
    public string KodeField { get; set; }

    [Column("VDeskfield")]
    [StringLength(50)]
    [Unicode(false)]
    public string DeskField { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }

    [Column("Keterangan")]
    [StringLength(50)]
    [Unicode(false)]
    public string Keterangan { get; set; }

    [ForeignKey("IdFieldgroup")]
    [InverseProperty("L_Standartfields")]
    public virtual L_StandartfieldGroup IdFieldgroupNavigation { get; set; }
}