// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_TarifPelayanan")]
[Index("Kodetariflayan", Name = "IX_L_SettingKomputerAntrian_vnmkomp", IsUnique = true)]
public partial class L_TarifPelayanan
{
    [Key]
    [Column("IdTariflayan")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdTariflayan { get; set; }

    [Column("KodeTarifLayan")]
    [StringLength(2)]
    [Unicode(false)]
    public string Kodetariflayan { get; set; }

    [Column("NamaTarifLayan")]
    [StringLength(50)]
    [Unicode(false)]
    public string Namatariflayan { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }

    [InverseProperty("VKodetariflayanNavigation")]
    public virtual ICollection<L_TarifDetail> L_Tarifdetails { get; set; } = new List<L_TarifDetail>();
}