// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_TarifRekananSub")]
public partial class L_TarifRekananSub
{
    [Key]
    [Column("IdTarifrekanansub")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid IdTarifrekanansub { get; set; }

    [Column("IdTarifRekananSub", TypeName = "numeric(18, 0)")]
    public decimal OldIdTarifRekananSub { get; set; }

    [Column("RekananIdHd", TypeName = "numeric(18, 0)")]
    public decimal RekananIdHd { get; set; }

    [Column("RekananidDt", TypeName = "numeric(18, 0)")]
    public decimal RekananidDt { get; set; }
}