// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_TarifDetail")]
public partial class L_TarifDetail
{
     [Key]
    [Column("IdTarifdetail")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid IdTarifdetail { get; set; }

    [Column("OldIdTarifdetail", TypeName = "numeric(18, 0)")]
    public decimal OldIdTarifdetail { get; set; }

    [Column("KodeTarifLayan")]
    [StringLength(2)]
    [Unicode(false)]
    public string KodeTarifLayan { get; set; }

    [Column("KdTarifDetail")]
    [StringLength(10)]
    [Unicode(false)]
    public string KdTarifDetail { get; set; }

    [Required]
    [Column("NmTarifDetail")]
    [StringLength(100)]
    [Unicode(false)]
    public string NmTarifDetail { get; set; }

    [Column("IsAktif")]
    public bool? IsAktif { get; set; }

    [Column("IdGroupTarif")]
    public int? IdGroupTarif { get; set; }

    [ForeignKey("IdGroupTarif")]
    [InverseProperty("L_Tarifdetails")]
    public virtual L_TarifGroup IdGrouptarifNavigation { get; set; }

    [ForeignKey("Kodetariflayan")]
    [InverseProperty("L_Tarifdetails")]
    public virtual L_TarifPelayanan VKodetariflayanNavigation { get; set; }
}