// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("L_Tindakan")]
public partial class L_Tindakan
{
    [Key]
    [Column("IdTindakan", TypeName = "numeric(18, 0)")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal IdTindakan { get; set; }

    [Column("KdTindakan")]
    [StringLength(8)]
    [Unicode(false)]
    public string Kdtindakan { get; set; }

    [Column("NmTindakan")]
    [StringLength(200)]
    [Unicode(false)]
    public string Nmtindakan { get; set; }

    [Column("NmPendek")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nmpendek { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }
}