// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("TM_GUDANG")]
[Index("IsRequest", Name = "IX_TM_GUDANG_ISREQUEST")]
[Index("IsAktif", Name = "IX_TM_GUDANG_IS_AKTIF")]
[Index("VKodeinventory", Name = "IX_TM_GUDANG_KDINV")]
[Index("IsListropp", Name = "IX_TM_GUDANG_LISROP")]
[Index("VNamagudangobat", Name = "IX_TM_GUDANG_NAMAGUDANG")]
public partial class TmGudang
{
    [Column("ID_GUDANGOBAT", TypeName = "numeric(18, 0)")]
    public decimal IdGudangobat { get; set; }

    [Key]
    [Column("V_KODEINVENTORY")]
    [StringLength(2)]
    [Unicode(false)]
    public string VKodeinventory { get; set; }

    [Column("V_NAMAGUDANGOBAT")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNamagudangobat { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [Column("IS_REQUEST")]
    public bool? IsRequest { get; set; }

    [Column("IS_LISTROPP")]
    public bool? IsListropp { get; set; }

    [Column("IS_TIPEBARANG")]
    [StringLength(1)]
    [Unicode(false)]
    public string IsTipebarang { get; set; }

    [Column("IS_PAKETBHP")]
    public bool? IsPaketbhp { get; set; }

    [Column("IS_RETURBHP")]
    public bool? IsReturbhp { get; set; }

    [InverseProperty("KodeRequestobatNavigation")]
    public virtual ICollection<TmRuang> TmRuangKodeRequestobatNavigations { get; set; } = new List<TmRuang>();

    [InverseProperty("VKodeinventoryNavigation")]
    public virtual ICollection<TmRuang> TmRuangVKodeinventoryNavigations { get; set; } = new List<TmRuang>();

    [InverseProperty("VKodetarifNavigation")]
    public virtual ICollection<TtHistoryStok> TtHistoryStoks { get; set; } = new List<TtHistoryStok>();

    [InverseProperty("VKodeinventoryNavigation")]
    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    [InverseProperty("VKoderequestobatNavigation")]
    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();

    [InverseProperty("VKodetarifNavigation")]
    public virtual ICollection<TtPaketPbApp> TtPaketPbAppVKodetarifNavigations { get; set; } = new List<TtPaketPbApp>();

    [InverseProperty("VKodetarifgdgNavigation")]
    public virtual ICollection<TtPaketPbApp> TtPaketPbAppVKodetarifgdgNavigations { get; set; } = new List<TtPaketPbApp>();

    [InverseProperty("VKodetarifNavigation")]
    public virtual ICollection<TtPaketPbPakai> TtPaketPbPakais { get; set; } = new List<TtPaketPbPakai>();

    [InverseProperty("VKodetarifNavigation")]
    public virtual ICollection<TtPaketPbRetur> TtPaketPbReturVKodetarifNavigations { get; set; } = new List<TtPaketPbRetur>();

    [InverseProperty("VKodetarifgdgNavigation")]
    public virtual ICollection<TtPaketPbRetur> TtPaketPbReturVKodetarifgdgNavigations { get; set; } = new List<TtPaketPbRetur>();

    [InverseProperty("VKodetarifNavigation")]
    public virtual ICollection<TtReturApp> TtReturApps { get; set; } = new List<TtReturApp>();

    [InverseProperty("VKodetarifNavigation")]
    public virtual ICollection<TtReturDist> TtReturDists { get; set; } = new List<TtReturDist>();
}