// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("TT_DIAGNOSAREKAP")]
public partial class TtDiagnosarekap
{
    [Key]
    [Column("ID_DIAGNOSAREKAP", TypeName = "numeric(18, 0)")]
    public decimal IdDiagnosarekap { get; set; }

    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("D_TGL", TypeName = "datetime")]
    public DateTime? DTgl { get; set; }

    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("V_NMDOKTER")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmdokter { get; set; }

    [Column("V_LAIN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VLain { get; set; }

    [Column("V_KODETARIF")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKodetarif { get; set; }

    [Column("D_TGLRM", TypeName = "datetime")]
    public DateTime? DTglrm { get; set; }

    [Column("V_KDMASUK")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdmasuk { get; set; }

    [Column("V_NMMASUK")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmmasuk { get; set; }

    [Column("V_KDUTAMA")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdutama { get; set; }

    [Column("V_NMUTAMA")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmutama { get; set; }

    [Column("V_KDKOMPLIKASI")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdkomplikasi { get; set; }

    [Column("V_NMKOMPLIKASI")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmkomplikasi { get; set; }

    [Column("V_KDSEKUNDER")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdsekunder { get; set; }

    [Column("V_NMSEKUNDER")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmsekunder { get; set; }

    [Column("V_KDOPERASI")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdoperasi { get; set; }

    [Column("V_NMOPERASI")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmoperasi { get; set; }

    [ForeignKey("IdRegistrasi")]
    [InverseProperty("TtDiagnosarekaps")]
    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }
}