// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("TT_KUITANSI")]
public partial class TtKuitansi
{
    [Key]
    [Column("ID", TypeName = "numeric(18, 0)")]
    public decimal Id { get; set; }

    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("V_TERIMADARI")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTerimadari { get; set; }

    [Column("V_KETERANGAN", TypeName = "text")]
    public string VKeterangan { get; set; }

    [Column("D_NOMINAL", TypeName = "decimal(18, 0)")]
    public decimal? DNominal { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }
}