// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("TT_KUITANSIRESEP")]
[Index("IdKuitansiresep", Name = "IX_TT_KUITANSIRESEP")]
[Index("IdRegistrasi", Name = "IX_TT_KUITANSIRESEP_1")]
[Index("VNmdokter", Name = "IX_TT_KUITANSIRESEP_2")]
[Index("VKoderuangan", Name = "IX_TT_KUITANSIRESEP_3")]
[Index("VKoderequestobat", Name = "IX_TT_KUITANSIRESEP_4")]
[Index("VKodetarif", Name = "IX_TT_KUITANSIRESEP_5")]
[Index("VKddokter", Name = "IX_TT_KUITANSIRESEP_6")]
[Index("Idn", Name = "IX_TT_KUITANSIRESEP_idn")]
[Index("VNoresep", Name = "IX_TT_KUITANSIRESEP_noresep")]
[Index("VStatus", Name = "IX_TT_KUITANSIRESEP_status")]
[Index("Statusnotif", Name = "IX_TT_KUITANSIRESEP_statusnotif")]
[Index("DTgl", Name = "IX_TT_KUITANSIRESEP_tgl")]
[Index("VTiperesep", Name = "IX_TT_KUITANSIRESEP_tiperesep")]
public partial class TtKuitansiresep
{
    [Column("IDN", TypeName = "numeric(18, 0)")]
    public decimal Idn { get; set; }

    [Key]
    [Column("ID_KUITANSIRESEP")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdKuitansiresep { get; set; }

    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("V_NMDOKTER")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmdokter { get; set; }

    [Column("D_TGL", TypeName = "datetime")]
    public DateTime? DTgl { get; set; }

    [Column("V_KODETARIF")]
    [StringLength(2)]
    [Unicode(false)]
    public string VKodetarif { get; set; }

    [Column("V_KODERUANGAN")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKoderuangan { get; set; }

    [Column("V_NORESEP")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNoresep { get; set; }

    [Column("V_TIPERESEP")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTiperesep { get; set; }

    [Column("V_STATUS")]
    [StringLength(50)]
    [Unicode(false)]
    public string VStatus { get; set; }

    [Column("STATUSNOTIF")]
    [StringLength(5)]
    [Unicode(false)]
    public string Statusnotif { get; set; }

    [Column("V_KODEREQUESTOBAT")]
    [StringLength(2)]
    [Unicode(false)]
    public string VKoderequestobat { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("C_APPROVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("D_APPROVE", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("V_APPROVE_AA")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveAa { get; set; }

    [Column("C_APPROVE_AA")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveAa { get; set; }

    [Column("D_APPROVE_AA", TypeName = "datetime")]
    public DateTime? DApproveAa { get; set; }

    [Column("V_APPROVE_VER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [Column("C_APPROVE_VER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("D_APPROVE_VER", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [Required]
    [Column("TTD_DOKTER", TypeName = "text")]
    public string TtdDokter { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("TtKuitansireseps")]
    public virtual TmStatus IdStatusNavigation { get; set; }

    [ForeignKey("VKddokter")]
    [InverseProperty("TtKuitansireseps")]
    public virtual TmDokter VKddokterNavigation { get; set; }

    [ForeignKey("VKoderequestobat")]
    [InverseProperty("TtKuitansireseps")]
    public virtual TmGudang VKoderequestobatNavigation { get; set; }

    [ForeignKey("VKoderuangan")]
    [InverseProperty("TtKuitansireseps")]
    public virtual TmRuang VKoderuanganNavigation { get; set; }
}