// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;;

[Table("TT_PAKET_PB_PAKAI_DETAIL")]
public partial class TtPaketPbPakaiDetail
{
    [Key]
    [Column("ID_PAKETPB_PAKAIDETAIL", TypeName = "numeric(18, 0)")]
    public decimal IdPaketpbPakaidetail { get; set; }

    [Column("ID_PAKETPB_PAKAI", TypeName = "numeric(18, 0)")]
    public decimal? IdPaketpbPakai { get; set; }

    [Column("ID_BARANG", TypeName = "numeric(18, 0)")]
    public decimal? IdBarang { get; set; }

    [Column("D_JML", TypeName = "decimal(18, 2)")]
    public decimal? DJml { get; set; }

    [Column("D_JMLPAKAI", TypeName = "decimal(18, 2)")]
    public decimal? DJmlpakai { get; set; }

    [Column("D_HARGAJUAL", TypeName = "decimal(18, 0)")]
    public decimal? DHargajual { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [Column("V_APPROVE_VER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [Column("C_APPROVE_VER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("D_APPROVE_VER", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [ForeignKey("IdPaketpbPakai")]
    [InverseProperty("TtPaketPbPakaiDetails")]
    public virtual TtPaketPbPakai IdPaketpbPakaiNavigation { get; set; }
}