// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("TT_PAKET_PB_RETUR_DETAIL")]
public partial class TtPaketPbReturDetail
{
    [Key]
    [Column("ID_PAKETPB_RETURDETAIL", TypeName = "numeric(18, 0)")]
    public decimal IdPaketpbReturdetail { get; set; }

    [Column("ID_PAKETPB_RETUR", TypeName = "numeric(18, 0)")]
    public decimal? IdPaketpbRetur { get; set; }

    [Column("ID_BARANG", TypeName = "numeric(18, 0)")]
    public decimal? IdBarang { get; set; }

    [Column("D_JML", TypeName = "decimal(18, 2)")]
    public decimal? DJml { get; set; }

    [Column("D_JMLPAKAI", TypeName = "decimal(18, 2)")]
    public decimal? DJmlpakai { get; set; }

    [Column("D_SISA", TypeName = "decimal(18, 2)")]
    public decimal? DSisa { get; set; }

    [Column("D_HARGAJUAL", TypeName = "decimal(18, 0)")]
    public decimal? DHargajual { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [ForeignKey("IdPaketpbRetur")]
    [InverseProperty("TtPaketPbReturDetails")]
    public virtual TtPaketPbRetur IdPaketpbReturNavigation { get; set; }
}