// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("TT_PEMBAYARAN")]
[Index("DTgl", Name = "IX_TT_PEMBAYARAN")]
[Index("VNomorbyrpasien", Name = "IX_TT_PEMBAYARAN_1")]
[Index("VBy", Name = "IX_TT_PEMBAYARAN_2")]
[Index("DJumlah", Name = "IX_TT_PEMBAYARAN_3")]
public partial class TtPembayaran
{
    [Column("IDPEMBAYARAN", TypeName = "numeric(18, 0)")]
    public decimal Idpembayaran { get; set; }

    [Key]
    [Column("V_NOMORBYRPASIEN")]
    [StringLength(12)]
    [Unicode(false)]
    public string VNomorbyrpasien { get; set; }

    [Required]
    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("D_TGL", TypeName = "datetime")]
    public DateTime DTgl { get; set; }

    [Column("D_JUMLAH", TypeName = "decimal(18, 0)")]
    public decimal? DJumlah { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }
}