// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[PrimaryKey("IdPasienlab", "VKdpemeriksaanlab")]
[Table("TT_PEMERIKSAANPA")]
public partial class TtPemeriksaanpa
{
    [Key]
    [Column("ID_PASIENLAB")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdPasienlab { get; set; }

    [Column("V_BAHAN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VBahan { get; set; }

    [Key]
    [Column("V_KDPEMERIKSAANLAB")]
    [StringLength(8)]
    [Unicode(false)]
    public string VKdpemeriksaanlab { get; set; }

    [Column("V_NMPEMERIKSAAN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmpemeriksaan { get; set; }

    [Column("V_RINGKASAN", TypeName = "text")]
    public string VRingkasan { get; set; }

    [Column("V_DIAGNOSA")]
    [StringLength(500)]
    [Unicode(false)]
    public string VDiagnosa { get; set; }

    [Column("V_PERIKSAKEMARIN", TypeName = "text")]
    public string VPeriksakemarin { get; set; }

    [Column("D_TGLTERIMA", TypeName = "datetime")]
    public DateTime? DTglterima { get; set; }

    [Column("D_TGLJAWABAN", TypeName = "datetime")]
    public DateTime? DTgljawaban { get; set; }

    [Column("V_MAKRO", TypeName = "text")]
    public string VMakro { get; set; }

    [Column("V_MIKRO", TypeName = "text")]
    public string VMikro { get; set; }

    [Column("V_KESIMPULAN", TypeName = "text")]
    public string VKesimpulan { get; set; }

    [Column("V_SARAN", TypeName = "text")]
    public string VSaran { get; set; }

    [Column("V_CATATAN", TypeName = "text")]
    public string VCatatan { get; set; }

    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("V_NMDOKTER")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmdokter { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [ForeignKey("VKddokter")]
    [InverseProperty("TtPemeriksaanpas")]
    public virtual TmDokter VKddokterNavigation { get; set; }
}