// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("TT_RETUR")]
[Index("DJml", Name = "IX_TT_RETUR_d_jml")]
[Index("DTglretur", Name = "IX_TT_RETUR_d_tglretur")]
[Index("IdResep", Name = "IX_TT_RETUR_idresep")]
[Index("IdReturdetail", Name = "IX_TT_RETUR_idreturdetail")]
[Index("VBy", Name = "IX_TT_RETUR_v_by")]
[Index("DHarga", Name = "d_harga")]
public partial class TtRetur
{
    [Key]
    [Column("ID_RETURDETAIL", TypeName = "numeric(18, 0)")]
    public decimal IdReturdetail { get; set; }

    [Column("V_NOMORRETUR")]
    [StringLength(12)]
    [Unicode(false)]
    public string VNomorretur { get; set; }

    [Required]
    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Required]
    [Column("ID_RESEP")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdResep { get; set; }

    [Column("ID_BARANG", TypeName = "numeric(18, 0)")]
    public decimal? IdBarang { get; set; }

    [Required]
    [Column("V_KDOBAT")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdobat { get; set; }

    [Column("V_NMOBAT")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmobat { get; set; }

    [Column("D_JML", TypeName = "decimal(18, 0)")]
    public decimal? DJml { get; set; }

    [Column("D_HARGA", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("REKANANID", TypeName = "numeric(18, 0)")]
    public decimal? Rekananid { get; set; }

    [Column("C_APPROVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("V_APPROVE")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApprove { get; set; }

    [Column("D_APPROVE", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("D_TGLRETUR", TypeName = "datetime")]
    public DateTime? DTglretur { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("V_NOTE")]
    [StringLength(200)]
    [Unicode(false)]
    public string VNote { get; set; }

    [Column("V_STATUS")]
    [StringLength(1)]
    [Unicode(false)]
    public string VStatus { get; set; }

    [Column("V_SETTINGRETUR")]
    [StringLength(15)]
    [Unicode(false)]
    public string VSettingretur { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [Column("C_APPROVE_VER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("V_APPROVE_VER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [Column("D_APPROVE_VER", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("TtReturs")]
    public virtual TmStatus IdStatusNavigation { get; set; }

    [ForeignKey("VNomorretur")]
    [InverseProperty("TtReturs")]
    public virtual TtKuitansiretur VNomorreturNavigation { get; set; }
}