// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.NewModels;

[Table("TT_TINDAKAN")]
[Index("DTgltindakan", Name = "IX_TT_TINDAKAN")]
[Index("IdRegistrasi", Name = "IX_TT_TINDAKAN_1")]
[Index("VNomortindakan", Name = "IX_TT_TINDAKAN_2")]
[Index("VKodetarif", Name = "IX_TT_TINDAKAN_3")]
public partial class TtTindakan
{
    [Key]
    [Column("ID_TINDAKAN", TypeName = "numeric(18, 0)")]
    public decimal IdTindakan { get; set; }

    [Column("V_NOMORTINDAKAN")]
    [StringLength(12)]
    [Unicode(false)]
    public string VNomortindakan { get; set; }

    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("D_TGLTINDAKAN", TypeName = "datetime")]
    public DateTime? DTgltindakan { get; set; }

    [Column("V_NOTE")]
    [StringLength(300)]
    [Unicode(false)]
    public string VNote { get; set; }

    [Column("V_KODETARIF")]
    [StringLength(2)]
    [Unicode(false)]
    public string VKodetarif { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("C_APPROVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("D_APPROVE", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("V_APPROVE")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApprove { get; set; }

    [Column("C_APPROVE2")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove2 { get; set; }

    [Column("D_APPROVE2", TypeName = "datetime")]
    public DateTime? DApprove2 { get; set; }

    [Column("V_STATUS")]
    [StringLength(20)]
    [Unicode(false)]
    public string VStatus { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [ForeignKey("IdRegistrasi")]
    [InverseProperty("TtTindakans")]
    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("TtTindakans")]
    public virtual TmStatus IdStatusNavigation { get; set; }
}