// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmAntrianCounterAudio
{
    public decimal IdCounteraudio { get; set; }

    public string VKdcounter { get; set; }

    public string VCounter { get; set; }

    public bool? IsAktif { get; set; }

    public string VKdlokasi { get; set; }

    public string VKdlayanan { get; set; }

    public string VFile { get; set; }

    public string VNomor { get; set; }
}