// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmAntrianLayanan
{
    public decimal IdLayanan { get; set; }

    public string VKdlayanan { get; set; }

    public string VLayanan { get; set; }

    public bool? IsAktif { get; set; }

    public string VInisial { get; set; }

    public string VKdlokasi { get; set; }
}