// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmBank
{
    public decimal IdBank { get; set; }

    public string VKdbank { get; set; }

    public string VNmbank { get; set; }

    public string VCabang { get; set; }

    public string VAlamat { get; set; }

    public string VKota { get; set; }

    public string VTelepon { get; set; }

    public bool IsAktif { get; set; }

    public string VNomorrekening { get; set; }

    public string VKdakun { get; set; }
}