// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmCoaKlasifikasi
{
    public decimal IdKlasifikasi { get; set; }

    public string VNmklasifikasi { get; set; }

    public decimal? VUrut { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGolongan { get; set; }

    public virtual TmCoaGolongan IdGolonganNavigation { get; set; }

    public virtual ICollection<TmCoaSubklasifikasi> TmCoaSubklasifikasis { get; set; } = new List<TmCoaSubklasifikasi>();
}