// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmCoa
{
    public decimal IdCoa { get; set; }

    public string VKdakun { get; set; }

    public string VNmakun { get; set; }

    public string VNmakunalias { get; set; }

    public string VDc { get; set; }

    public DateTime? DTglsaldoawal { get; set; }

    public decimal? DSaldoawal { get; set; }

    public decimal? IdSubklasifikasi { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmCoaSubklasifikasi IdSubklasifikasiNavigation { get; set; }

    public virtual ICollection<TmDokter> TmDokters { get; set; } = new List<TmDokter>();
}