// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmCounttraffic
{
    public decimal Idcounttraffic { get; set; }

    public DateTime? Tanggal { get; set; }

    public string Jam { get; set; }

    public string Menu { get; set; }

    public string Submenu { get; set; }

    public string VBy { get; set; }
}