// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmCoaGolongan
{
    public decimal IdGolongan { get; set; }

    public string VNmgolongan { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmCoaKlasifikasi> TmCoaKlasifikasis { get; set; } = new List<TmCoaKlasifikasi>();
}