// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmDepartement
{
    public decimal IdDepartment { get; set; }

    public string NamaDepartemen { get; set; }
}