// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmFarmakoterapi
{
    public decimal IdFarmakoterapi { get; set; }

    public string VNmfarmakoterapi { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmBarang> TmBarangs { get; set; } = new List<TmBarang>();

    public virtual ICollection<TmFarmakoterapiSub> TmFarmakoterapiSubs { get; set; } = new List<TmFarmakoterapiSub>();
}