// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmGizi
{
    public decimal IdGizi { get; set; }

    public string VKdmakanan { get; set; }

    public string VNmmakanan { get; set; }

    public string VGroup { get; set; }

    public string VNote { get; set; }

    public string VKandungan { get; set; }

    public decimal? DEnergi { get; set; }

    public decimal? DProtein { get; set; }

    public decimal? DLemak { get; set; }

    public decimal? DKh { get; set; }

    public decimal? DCalsium { get; set; }

    public decimal? DFosfor { get; set; }

    public decimal? DFe { get; set; }

    public decimal? DVita { get; set; }

    public decimal? DVitb1 { get; set; }

    public decimal? DVitc { get; set; }

    public decimal? DAir { get; set; }

    public decimal? DBdd { get; set; }

    public bool? IsAktif { get; set; }
}