// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmGudang
{
    public decimal IdGudangobat { get; set; }

    public string VKodeinventory { get; set; }

    public string VNamagudangobat { get; set; }

    public bool? IsAktif { get; set; }

    public bool? IsRequest { get; set; }

    public bool? IsListropp { get; set; }

    public string IsTipebarang { get; set; }

    public bool? IsPaketbhp { get; set; }

    public bool? IsReturbhp { get; set; }

    public virtual ICollection<TmRuang> TmRuangKodeRequestobatNavigations { get; set; } = new List<TmRuang>();

    public virtual ICollection<TmRuang> TmRuangVKodeinventoryNavigations { get; set; } = new List<TmRuang>();
}