// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmHargarekanan
{
    public decimal Idhargarekanan { get; set; }

    public decimal? Barangid { get; set; }

    public decimal? Rekananid { get; set; }

    public decimal? Harga { get; set; }

    public DateTime? Lastupdate { get; set; }

    public string Inpuby { get; set; }

    public decimal? Margin { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Ppn { get; set; }

    public decimal? Hargajual { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmBarang Barang { get; set; }

    public virtual TmRekanan Rekanan { get; set; }
}