// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmHasilrad
{
    public decimal IdNumhasilrad { get; set; }

    public string VKdpemeriksaanrad { get; set; }

    public int INoitem { get; set; }

    public string VNmitem { get; set; }

    public string VHasilstandar { get; set; }

    public string VNote { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }
}