// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmHargakamar
{
    public decimal IdHargakamar { get; set; }

    public string VKelas { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmKamarinap> TmKamarinaps { get; set; } = new List<TmKamarinap>();

    public virtual ICollection<TmLaboratoriumHarga> TmLaboratoriumHargas { get; set; } = new List<TmLaboratoriumHarga>();

    public virtual ICollection<TmRadiologiHarga> TmRadiologiHargas { get; set; } = new List<TmRadiologiHarga>();
}