// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmHasillab
{
    public decimal IdNumhasillab { get; set; }

    public string VKdpemeriksaanlab { get; set; }

    public int IdHasillab { get; set; }

    public string VNmhasil { get; set; }

    public string VHasil { get; set; }

    public string VNistandart { get; set; }

    public string VSatuan { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }
}