// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmhKamar
{
    public decimal Idkamar { get; set; }

    public string Kamar { get; set; }

    public string Kelas { get; set; }

    public decimal? Harga { get; set; }

    public string Status { get; set; }

    public bool? IsAktif { get; set; }

    public string VKoderuangan { get; set; }
}