// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmKamarinapRekanan
{
    public decimal IdKamarinaprek { get; set; }

    public string VKdtmptidur { get; set; }

    public decimal Rekananid { get; set; }

    public bool? IsAktif { get; set; }
}