// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmKamarinap
{
    public decimal IdKamarinap { get; set; }

    public string VKdtmptidur { get; set; }

    public string VKelas { get; set; }

    public string VLantai { get; set; }

    public string VNokamar { get; set; }

    public string VKodetarif { get; set; }

    public string VKoderuangan { get; set; }

    public string CIsi { get; set; }

    public int? IX { get; set; }

    public int? IY { get; set; }

    public decimal? IdMapid { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmMap IdMap { get; set; }

    public virtual ICollection<TmKamarinapHarga> TmKamarinapHargas { get; set; } = new List<TmKamarinapHarga>();

    public virtual TmHargakamar VKelasNavigation { get; set; }
}