// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmKelompokbarang
{
    public decimal Kelompokid { get; set; }

    public string Kode { get; set; }

    public string Nama { get; set; }

    public decimal? Margin { get; set; }

    public string Note { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGrouptarif { get; set; }

    public virtual ICollection<TmBarang> TmBarangs { get; set; } = new List<TmBarang>();
}