// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmLaboratorium
{
    public decimal IdPemeriksaanlab { get; set; }

    public string VKdpemeriksaanlab { get; set; }

    public string VNmpemeriksaanlab { get; set; }

    public decimal? IdGroup { get; set; }

    public bool? CIsaktif { get; set; }

    public virtual TmLaboratoriumGroup IdGroupNavigation { get; set; }

    public virtual ICollection<TmLaboratoriumHarga> TmLaboratoriumHargas { get; set; } = new List<TmLaboratoriumHarga>();

    public virtual ICollection<TmLaboratoriumRekanan> TmLaboratoriumRekanans { get; set; } = new List<TmLaboratoriumRekanan>();
}