// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmLaboratoriumRekanan
{
    public decimal IdLabrekanan { get; set; }

    public string VKdpemeriksaanlab { get; set; }

    public decimal Rekananid { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmRekanan Rekanan { get; set; }

    public virtual TmLaboratorium VKdpemeriksaanlabNavigation { get; set; }
}