// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmLaboratoriumHarga
{
    public decimal IdLabharga { get; set; }

    public string VKdpemeriksaanlab { get; set; }

    public decimal Rekananid { get; set; }

    public string VKelas { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DJasamedis { get; set; }

    public decimal? DJasars { get; set; }

    public decimal? DBahanalkes { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DCito { get; set; }

    public decimal? DPenyulit { get; set; }

    public decimal? D2tnd { get; set; }

    public decimal? DAdm { get; set; }

    public DateTime? DTglawal { get; set; }

    public DateTime? DTglakhir { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }

    public DateTime? DLastupdate { get; set; }

    public virtual TmRekanan Rekanan { get; set; }

    public virtual TmLaboratorium VKdpemeriksaanlabNavigation { get; set; }

    public virtual TmHargakamar VKelasNavigation { get; set; }
}