// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmLaboratoriumGroup
{
    public decimal IdGroup { get; set; }

    public string VNmgroup { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGrouptarif { get; set; }

    public bool? IsPk { get; set; }

    public virtual ICollection<TmLaboratorium> TmLaboratoria { get; set; } = new List<TmLaboratorium>();
}