// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmMasterTnd2
{
    public string VNmgrouptarif { get; set; }

    public string VNmtarifdetail { get; set; }

    public string VKdtarifdetail { get; set; }

    public decimal? Rekananid { get; set; }

    public string VKelas { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DCito { get; set; }

    public decimal? DPenyulit { get; set; }

    public decimal? D2tnd { get; set; }

    public decimal? DAdm { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DJasamedis { get; set; }

    public decimal? DJasamedis2 { get; set; }

    public decimal? DJasamedis3 { get; set; }

    public decimal? DJasamedis4 { get; set; }

    public decimal? DJasamedis5 { get; set; }

    public decimal? DJasars { get; set; }

    public decimal? DBahanalkes { get; set; }
}