// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmMap
{
    public decimal IdMapid { get; set; }

    public string VNmmap { get; set; }

    public string VKoderuangan { get; set; }

    public string VNote { get; set; }

    public byte[] IImage { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmKamarinap> TmKamarinaps { get; set; } = new List<TmKamarinap>();

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}