// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmMasterRad2
{
    public string VNmgroup { get; set; }

    public string VNmpemeriksaanrad { get; set; }

    public decimal? IdRadharga { get; set; }

    public string VKdpemeriksaanrad { get; set; }

    public decimal? Rekananid { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public string VKelas { get; set; }
}