// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmMasterPaketH
{
    public decimal Id { get; set; }

    public decimal? Idmasterpemeriksaan { get; set; }

    public string VNmpemeriksaan { get; set; }

    public string VKdpemeriksaan { get; set; }

    public decimal? DHarga { get; set; }

    public string VPenunjang { get; set; }

    public decimal? IdGrouptarif { get; set; }
}