// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmMasterTnd
{
    public double? IdGrouptarif { get; set; }

    public string VNmgrouptarif { get; set; }

    public string VKdtarifdetail { get; set; }

    public string VNmtarifdetail { get; set; }

    public string VKelas { get; set; }

    public double? DHarga { get; set; }

    public double? IsAktif { get; set; }

    public double? DHargaBpjs { get; set; }
}