// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmModuleDetail
{
    public decimal IdModuledetail { get; set; }

    public decimal? IdModule { get; set; }

    public string VNmmoduldetail { get; set; }

    public string VNmmoduledetailsub { get; set; }

    public decimal? VUrut { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmModule IdModuleNavigation { get; set; }
}