// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmModule
{
    public decimal IdModule { get; set; }

    public string VNmmodule { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmModuleDetail> TmModuleDetails { get; set; } = new List<TmModuleDetail>();
}