// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmPaketMatrix
{
    public decimal IdPaketmatrix { get; set; }

    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    public string VKoderuangan { get; set; }

    public bool? IsAktif { get; set; }
}