// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmPaketdetail
{
    public decimal IdPaketdetail { get; set; }

    public string VKdpaketdetail { get; set; }

    public string VNmpaketdetail { get; set; }

    public string VGroup { get; set; }

    public string VTipe { get; set; }

    public decimal? DHarga { get; set; }

    public string Rekanan { get; set; }
}