// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmRadiologi
{
    public decimal IdPemeriksaanrad { get; set; }

    public string VKdpemeriksaanrad { get; set; }

    public string VNmpemeriksaanrad { get; set; }

    public decimal? IdGroup { get; set; }

    public bool? CIsaktif { get; set; }

    public virtual TmRadiologiGroup IdGroupNavigation { get; set; }

    public virtual ICollection<TmRadiologiHarga> TmRadiologiHargas { get; set; } = new List<TmRadiologiHarga>();

    public virtual ICollection<TmRadiologiRekanan> TmRadiologiRekanans { get; set; } = new List<TmRadiologiRekanan>();
}