// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmRadiologiRekanan
{
    public decimal IdRadrekanan { get; set; }

    public string VKdpemeriksaanrad { get; set; }

    public decimal Rekananid { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmRekanan Rekanan { get; set; }

    public virtual TmRadiologi VKdpemeriksaanradNavigation { get; set; }
}