// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmRadiologiGroup
{
    public decimal IdGroup { get; set; }

    public string VNmgroup { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGrouptarif { get; set; }

    public virtual ICollection<TmRadiologi> TmRadiologis { get; set; } = new List<TmRadiologi>();
}