// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmRekanan
{
    public decimal IdNumrekanan { get; set; }

    public decimal Rekananid { get; set; }

    public string VNmrekanan { get; set; }

    public string VAlamat { get; set; }

    public string VKota { get; set; }

    public string VTelp { get; set; }

    public string VAlias { get; set; }

    public bool? IsAktif { get; set; }

    public string VKdakun { get; set; }

    public bool? IsPaketbhp { get; set; }

    public bool? IsTarif { get; set; }

    public bool? IsTarifnonmed { get; set; }

    public bool? IsCob { get; set; }

    public virtual ICollection<TmHargarekanan> TmHargarekanans { get; set; } = new List<TmHargarekanan>();

    public virtual ICollection<TmLaboratoriumHarga> TmLaboratoriumHargas { get; set; } = new List<TmLaboratoriumHarga>();

    public virtual ICollection<TmLaboratoriumRekanan> TmLaboratoriumRekanans { get; set; } = new List<TmLaboratoriumRekanan>();

    public virtual ICollection<TmPasien> TmPasiens { get; set; } = new List<TmPasien>();

    public virtual ICollection<TmRadiologiHarga> TmRadiologiHargas { get; set; } = new List<TmRadiologiHarga>();

    public virtual ICollection<TmRadiologiRekanan> TmRadiologiRekanans { get; set; } = new List<TmRadiologiRekanan>();
}