// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSettingKomputerAntrian
{
    public decimal IdSettingkomp { get; set; }

    public string VNmkomputer { get; set; }

    public string VKdlokasi { get; set; }

    public string VKdjenislayanan { get; set; }

    public string VKdcounter { get; set; }

    public DateTime? DTanggal { get; set; }
}