// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSettingBayar
{
    public decimal IdSettingBayar { get; set; }

    public string VCarabayar { get; set; }

    public string VKdakun { get; set; }
}