// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSettingAdm
{
    public decimal IdNumadm { get; set; }

    public decimal? Rekananid { get; set; }

    public string VKategori { get; set; }

    public decimal? DBiaya { get; set; }

    public decimal? DPercent { get; set; }
}