// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSettingPrshn
{
    public decimal IdPerusahaan { get; set; }

    public string VKdperusahaan { get; set; }

    public string VNmperusahaan { get; set; }

    public string VAlamat { get; set; }

    public string VTelp { get; set; }

    public string VWebsite { get; set; }

    public string VEmail { get; set; }

    public string VLogo { get; set; }

    public string VCodelogo { get; set; }
}