// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSeptember2015
{
    public decimal? Barangid { get; set; }

    public string Nama { get; set; }

    public decimal? Supplier { get; set; }

    public decimal? Harga { get; set; }
}