// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSmf
{
    public decimal IdSmf { get; set; }

    public string VKdsmf { get; set; }

    public string VNmsmf { get; set; }

    public bool? IsAktif { get; set; }
}