// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmStandartfield
{
    public decimal IdField { get; set; }

    public decimal? IdFieldgroup { get; set; }

    public string VKodefield { get; set; }

    public string VDeskfield { get; set; }

    public bool? IsAktif { get; set; }

    public string VKeterangan { get; set; }

    public virtual TmStandartfieldGroup IdFieldgroupNavigation { get; set; }
}