// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmSupplier
{
    public decimal Supplierid { get; set; }

    public string Namasupplier { get; set; }

    public string Alamat { get; set; }

    public string Cp { get; set; }

    public string Fax { get; set; }

    public string Kota { get; set; }

    public string Telpon { get; set; }

    public string Note { get; set; }

    public bool? Isaktif { get; set; }

    public string VKdakun { get; set; }

    public virtual ICollection<TmHargabarang> TmHargabarangs { get; set; } = new List<TmHargabarang>();
}