// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmTarifnonmedisHarga
{
    public decimal IdNonmedishrg { get; set; }

    public string VKdtarif { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? IdRekanan { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmTarifnonmedi VKdtarifNavigation { get; set; }
}