// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmUserGroup
{
    public decimal IdGroupuser { get; set; }

    public string VNmgroupuser { get; set; }

    public virtual ICollection<TmUser> TmUsers { get; set; } = new List<TmUser>();
}