// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WincareMigrations.Models;

public partial class TmUser
{
    public decimal IdNumuser { get; set; }

    public string VKoderuangan { get; set; }

    public string VNamalengkap { get; set; }

    public string VNmuser { get; set; }

    public string VPassword { get; set; }

    public string VKddokter { get; set; }

    public bool? BIsuser { get; set; }

    public bool? BIsmanager { get; set; }

    public bool? BIsadmin { get; set; }

    public bool? BIsmod { get; set; }

    public bool? BIsdokter { get; set; }

    public bool? BIsmemo { get; set; }

    public decimal? IdGroupuser { get; set; }

    public string IsTtd { get; set; }

    public bool? CIsaktif { get; set; }

    public string Id { get; set; }

    public bool? Transmigrated { get; set; }

    public string IdKaryawan { get; set; }

    public decimal? Pin { get; set; }

    public virtual TmUserGroup IdGroupuserNavigation { get; set; }

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}