// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TmDokterNote
{
    public decimal IdDokter { get; set; }

    public string VKddokter { get; set; }

    public string Keterangan { get; set; }

    public string VBy { get; set; }

    public DateTime? TglInput { get; set; }
}