// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TM_PASIEN")]
[Index("VAgamapasien", Name = "IX_TM_PASIEN_agama")]
[Index("VAlamatpasien", Name = "IX_TM_PASIEN_alamat")]
[Index("IsBlacklist", Name = "IX_TM_PASIEN_blacklist")]
[Index("VHppasien", Name = "IX_TM_PASIEN_hp")]
[Index("IdPasien", Name = "IX_TM_PASIEN_idpasien")]
[Index("IsAktif", Name = "IX_TM_PASIEN_isaktif")]
[Index("CKelaminpasien", Name = "IX_TM_PASIEN_kelamin")]
[Index("VKotapasien", Name = "IX_TM_PASIEN_kota")]
[Index("VNamapasien", Name = "IX_TM_PASIEN_namapasien")]
[Index("VNoktpsimpasien", Name = "IX_TM_PASIEN_noktp")]
[Index("VNopenjamin", Name = "IX_TM_PASIEN_nopenjamin")]
[Index("VPekerjaanpasien", Name = "IX_TM_PASIEN_pekerjaan")]
[Index("VStatuskwnpasien", Name = "IX_TM_PASIEN_statuskawin")]
[Index("VTelppasien", Name = "IX_TM_PASIEN_telp")]
[Index("VTmptlahirpasien", Name = "IX_TM_PASIEN_tempatlahir")]
[Index("DTgllahirpasien", Name = "IX_TM_PASIEN_tgllahir")]
[Index("IdNumpasien", Name = "idnumpasien")]
public partial class TmPasien
{
    [Column("ID_NUMPASIEN", TypeName = "numeric(18, 0)")]
    public decimal IdNumpasien { get; set; }

    [Key]
    [Column("ID_PASIEN")]
    [StringLength(10)]
    [Unicode(false)]
    public string IdPasien { get; set; }

    [Required]
    [Column("V_NAMAPASIEN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNamapasien { get; set; }

    [Column("V_NAMAKELPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNamakelpasien { get; set; }

    [Column("C_KELAMINPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string CKelaminpasien { get; set; }

    [Column("V_TMPTLAHIRPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTmptlahirpasien { get; set; }

    [Column("D_TGLLAHIRPASIEN", TypeName = "datetime")]
    public DateTime? DTgllahirpasien { get; set; }

    [Column("V_AGAMAPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VAgamapasien { get; set; }

    [Column("V_STATUSKWNPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VStatuskwnpasien { get; set; }

    [Column("V_PENDIDIKANPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VPendidikanpasien { get; set; }

    [Column("V_PEKERJAANPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VPekerjaanpasien { get; set; }

    [Column("V_ALAMATPEKERJAAN")]
    [StringLength(200)]
    [Unicode(false)]
    public string VAlamatpekerjaan { get; set; }

    [Column("V_TELPPEKERJAAN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VTelppekerjaan { get; set; }

    [Column("V_NOKTPSIMPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNoktpsimpasien { get; set; }

    [Column("V_JENISIDENTITAS")]
    [StringLength(50)]
    [Unicode(false)]
    public string VJenisidentitas { get; set; }

    [Column("V_NOPENJAMIN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNopenjamin { get; set; }

    [Column("V_ALAMATPASIEN")]
    [StringLength(200)]
    [Unicode(false)]
    public string VAlamatpasien { get; set; }

    [Column("V_KOTAPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VKotapasien { get; set; }

    [Column("V_TELPPASIEN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VTelppasien { get; set; }

    [Column("V_HPPASIEN")]
    [StringLength(20)]
    [Unicode(false)]
    public string VHppasien { get; set; }

    [Column("V_ALERGIPASIEN")]
    [StringLength(200)]
    [Unicode(false)]
    public string VAlergipasien { get; set; }

    [Column("V_CATKHUSPASIEN")]
    [StringLength(200)]
    [Unicode(false)]
    public string VCatkhuspasien { get; set; }

    [Column("V_AYAHPASIEN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VAyahpasien { get; set; }

    [Column("V_IBUPASIEN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VIbupasien { get; set; }

    [Column("V_PASANGANPASIEN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VPasanganpasien { get; set; }

    [Column("V_NAMAPENANGGUNG")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNamapenanggung { get; set; }

    [Column("V_ALAMATPENANGGUNG")]
    [StringLength(200)]
    [Unicode(false)]
    public string VAlamatpenanggung { get; set; }

    [Column("V_TELPPENANGGUNG")]
    [StringLength(100)]
    [Unicode(false)]
    public string VTelppenanggung { get; set; }

    [Column("V_KODEPOS")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKodepos { get; set; }

    [Column("V_PETUGAS")]
    [StringLength(50)]
    [Unicode(false)]
    public string VPetugas { get; set; }

    [Column("V_RHESUS")]
    [StringLength(10)]
    [Unicode(false)]
    public string VRhesus { get; set; }

    [Column("C_GOLDARAH")]
    [StringLength(3)]
    [Unicode(false)]
    public string CGoldarah { get; set; }

    [Column("D_TGLDAFTAR", TypeName = "datetime")]
    public DateTime? DTgldaftar { get; set; }

    [Column("C_ISCETAKKARTU")]
    [StringLength(1)]
    [Unicode(false)]
    public string CIscetakkartu { get; set; }

    [Column("V_WARGANEGARA")]
    [StringLength(50)]
    [Unicode(false)]
    public string VWarganegara { get; set; }

    [Column("V_JENISPASIEN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VJenispasien { get; set; }

    [Column("REKANANID", TypeName = "numeric(18, 0)")]
    public decimal? Rekananid { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [Column("V_SUKU")]
    [StringLength(50)]
    [Unicode(false)]
    public string VSuku { get; set; }

    [Column("V_PERUSAHAAN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VPerusahaan { get; set; }

    [Column("V_PROVINSI")]
    [StringLength(100)]
    [Unicode(false)]
    public string VProvinsi { get; set; }

    [Column("IS_BLACKLIST")]
    public bool? IsBlacklist { get; set; }

    [Column("IS_KUNJUNGAN")]
    public bool? IsKunjungan { get; set; }

    [ForeignKey("Rekananid")]
    [InverseProperty("TmPasiens")]
    public virtual TmRekanan Rekanan { get; set; }

    [InverseProperty("IdPasienNavigation")]
    public virtual ICollection<TtKunjungan> TtKunjungans { get; set; } = new List<TtKunjungan>();

    [InverseProperty("IdPasienNavigation")]
    public virtual ICollection<TtPasienRencanaRad> TtPasienRencanaRads { get; set; } = new List<TtPasienRencanaRad>();

    [InverseProperty("IdPasienNavigation")]
    public virtual ICollection<TtPenjadwalan> TtPenjadwalans { get; set; } = new List<TtPenjadwalan>();
}