// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TmPasien
{
    public decimal IdNumpasien { get; set; }

    public string IdPasien { get; set; }

    public string VNamapasien { get; set; }

    public string VNamakelpasien { get; set; }

    public string CKelaminpasien { get; set; }

    public string VTmptlahirpasien { get; set; }

    public DateTime? DTgllahirpasien { get; set; }

    public string VAgamapasien { get; set; }

    public string VStatuskwnpasien { get; set; }

    public string VPendidikanpasien { get; set; }

    public string VPekerjaanpasien { get; set; }

    public string VAlamatpekerjaan { get; set; }

    public string VTelppekerjaan { get; set; }

    public string VNoktpsimpasien { get; set; }

    public string VJenisidentitas { get; set; }

    public string VNopenjamin { get; set; }

    public string VAlamatpasien { get; set; }

    public string VKotapasien { get; set; }

    public string VTelppasien { get; set; }

    public string VHppasien { get; set; }

    public string VAlergipasien { get; set; }

    public string VCatkhuspasien { get; set; }

    public string VAyahpasien { get; set; }

    public string VIbupasien { get; set; }

    public string VPasanganpasien { get; set; }

    public string VNamapenanggung { get; set; }

    public string VAlamatpenanggung { get; set; }

    public string VTelppenanggung { get; set; }

    public string VKodepos { get; set; }

    public string VPetugas { get; set; }

    public string VRhesus { get; set; }

    public string CGoldarah { get; set; }

    public DateTime? DTgldaftar { get; set; }

    public string CIscetakkartu { get; set; }

    public string VWarganegara { get; set; }

    public string VJenispasien { get; set; }

    public decimal? Rekananid { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }

    public string VSuku { get; set; }

    public string VPerusahaan { get; set; }

    public string VProvinsi { get; set; }

    public bool? IsBlacklist { get; set; }

    public bool? IsKunjungan { get; set; }

    public virtual TmRekanan Rekanan { get; set; }

    public virtual ICollection<TtKunjungan> TtKunjungans { get; set; } = new List<TtKunjungan>();

    public virtual ICollection<TtPasienRencanaRad> TtPasienRencanaRads { get; set; } = new List<TtPasienRencanaRad>();

    public virtual ICollection<TtPenjadwalan> TtPenjadwalans { get; set; } = new List<TtPenjadwalan>();
}