// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TmRuang
{
    public decimal IdNumruang { get; set; }

    public string VKoderuangan { get; set; }

    public string Nama { get; set; }

    public string Noruang { get; set; }

    public string Kelompok { get; set; }

    public string Kamar { get; set; }

    public string VKodeinventory { get; set; }

    public string KodeRequestobat { get; set; }

    public string KodeTarif { get; set; }

    public bool? IsAktif { get; set; }

    public bool? IsTarif { get; set; }

    public string VGdgpaket { get; set; }

    public string VGdgretur { get; set; }

    public string VGdgpenerimaan { get; set; }

    public string VKdinhealth { get; set; }

    public string VLyninhealth { get; set; }

    public virtual TmGudang KodeRequestobatNavigation { get; set; }

    public virtual ICollection<TmJadwaldokter> TmJadwaldokters { get; set; } = new List<TmJadwaldokter>();

    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();

    public virtual ICollection<TtPasieninap> TtPasieninaps { get; set; } = new List<TtPasieninap>();

    public virtual ICollection<TtPasienlab> TtPasienlabs { get; set; } = new List<TtPasienlab>();

    public virtual ICollection<TtPasienpenunjang> TtPasienpenunjangs { get; set; } = new List<TtPasienpenunjang>();

    public virtual ICollection<TtPasienrad> TtPasienrads { get; set; } = new List<TtPasienrad>();

    public virtual ICollection<TtPasienugd> TtPasienugds { get; set; } = new List<TtPasienugd>();

    public virtual TmGudang VKodeinventoryNavigation { get; set; }
}