// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Wincare.Pendaftaran.Migration.NewModel;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TM_RUANG")]
[Index("VKoderuangan", Name = "IX_TM_RUANG")]
[Index("Nama", Name = "IX_TM_RUANG_1")]
[Index("Kamar", Name = "IX_TM_RUANG_2")]
[Index("VKodeinventory", Name = "IX_TM_RUANG_3")]
[Index("KodeRequestobat", Name = "IX_TM_RUANG_4")]
[Index("KodeTarif", Name = "IX_TM_RUANG_5")]
[Index("IsAktif", Name = "IX_TM_RUANG_6")]
[Index("IdNumruang", Name = "IX_TM_RUANG_7")]
[Index("VKdinhealth", Name = "IX_V_KDINHEALTH")]
[Index("VLyninhealth", Name = "IX_V_LYNINHEALTH")]
public partial class TmRuang
{
    [Column("ID_NUMRUANG", TypeName = "numeric(18, 0)")]
    public decimal IdNumruang { get; set; }

    [Key]
    [Column("V_KODERUANGAN")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKoderuangan { get; set; }

    [Required]
    [Column("NAMA")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nama { get; set; }

    [Column("NORUANG")]
    [StringLength(10)]
    [Unicode(false)]
    public string Noruang { get; set; }

    [Column("KELOMPOK")]
    [StringLength(1)]
    [Unicode(false)]
    public string Kelompok { get; set; }

    [Column("KAMAR")]
    [StringLength(10)]
    [Unicode(false)]
    public string Kamar { get; set; }

    [Column("V_KODEINVENTORY")]
    [StringLength(2)]
    [Unicode(false)]
    public string VKodeinventory { get; set; }

    [Column("KODE_REQUESTOBAT")]
    [StringLength(2)]
    [Unicode(false)]
    public string KodeRequestobat { get; set; }

    [Column("KODE_TARIF")]
    [StringLength(2)]
    [Unicode(false)]
    public string KodeTarif { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [Column("IS_TARIF")]
    public bool? IsTarif { get; set; }

    [Column("V_GDGPAKET")]
    [StringLength(2)]
    [Unicode(false)]
    public string VGdgpaket { get; set; }

    [Column("V_GDGRETUR")]
    [StringLength(2)]
    [Unicode(false)]
    public string VGdgretur { get; set; }

    [Column("V_GDGPENERIMAAN")]
    [StringLength(2)]
    [Unicode(false)]
    public string VGdgpenerimaan { get; set; }

    [Column("V_KDINHEALTH")]
    [StringLength(3)]
    [Unicode(false)]
    public string VKdinhealth { get; set; }

    [Column("V_LYNINHEALTH")]
    [StringLength(50)]
    [Unicode(false)]
    public string VLyninhealth { get; set; }

    [ForeignKey("KodeRequestobat")]
    [InverseProperty("TmRuangKodeRequestobatNavigations")]
    public virtual TmGudang KodeRequestobatNavigation { get; set; }

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TmJadwaldokter> TmJadwaldokters { get; set; } = new List<TmJadwaldokter>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasieninap> TtPasieninaps { get; set; } = new List<TtPasieninap>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienlab> TtPasienlabs { get; set; } = new List<TtPasienlab>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienpenunjang> TtPasienpenunjangs { get; set; } = new List<TtPasienpenunjang>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienrad> TtPasienrads { get; set; } = new List<TtPasienrad>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienugd> TtPasienugds { get; set; } = new List<TtPasienugd>();

    [ForeignKey("VKodeinventory")]
    [InverseProperty("TmRuangVKodeinventoryNavigations")]
    public virtual TmGudang VKodeinventoryNavigation { get; set; }
}