// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TmSettingDaftar
{
    public decimal IdSettingdaftar { get; set; }

    public string VNmunitdaftar { get; set; }

    public string VKoderuangan { get; set; }

    public string VTujuan { get; set; }

    public bool? IsTampil { get; set; }
}