// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TmTarifRekananSub
{
    public decimal IdTarifrekanansub { get; set; }

    public decimal RekananidHd { get; set; }

    public decimal RekananidDt { get; set; }
}