// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TrHasilrad
{
    public decimal IdTrhasilrad { get; set; }

    public string IdPasienrad { get; set; }

    public string VKdrad { get; set; }

    public string VNmpemeriksaan { get; set; }

    public string VHasil { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VBy { get; set; }

    public byte[] VRtf { get; set; }

    public DateTime? DTglinput { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtPasienrad IdPasienradNavigation { get; set; }
}