// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TrItemnonmedi
{
    public decimal IdItemnonmedis { get; set; }

    public decimal? IdTransaksinonmedis { get; set; }

    public string VKdtarif { get; set; }

    public string VNmtarif { get; set; }

    public string VGroup { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DJumlah { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DSubtotal { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public string VBy { get; set; }

    public virtual TtTransaksinonmedi IdTransaksinonmedisNavigation { get; set; }
}