// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TrItemobatlangsung
{
    public decimal IdItemobatlangsung { get; set; }

    public string VNokuitansi { get; set; }

    public string VKdobat { get; set; }

    public decimal? IdBarang { get; set; }

    public string VNoitem { get; set; }

    public string VNmobat { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DJumlah { get; set; }

    public decimal? DDiskon { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApprove { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public string VNoteobat { get; set; }

    public int? IdStatus { get; set; }

    public string VApproveVer { get; set; }

    public virtual TtObatlangsung VNokuitansiNavigation { get; set; }
}