// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TR_ITEMPAKET")]
public partial class TrItempaket
{
    [Key]
    [Column("ID_DETAILPAKET", TypeName = "numeric(18, 0)")]
    public decimal IdDetailpaket { get; set; }

    [Column("ID_PAKET", TypeName = "numeric(18, 0)")]
    public decimal? IdPaket { get; set; }

    [Column("V_NOMORPAKET")]
    [StringLength(12)]
    [Unicode(false)]
    public string VNomorpaket { get; set; }

    [Column("ID_MASTERPEMERIKSAANPENUNJANG", TypeName = "numeric(18, 0)")]
    public decimal? IdMasterpemeriksaanpenunjang { get; set; }

    [Column("ID_PENUNJANGDETAIL", TypeName = "numeric(18, 0)")]
    public decimal? IdPenunjangdetail { get; set; }

    [Column("V_KDDETAIL")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKddetail { get; set; }

    [Column("V_NMDETAIL")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmdetail { get; set; }

    [Column("V_GROUP")]
    [StringLength(100)]
    [Unicode(false)]
    public string VGroup { get; set; }

    [Column("V_TIPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTipe { get; set; }

    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("V_NMDOKTER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNmdokter { get; set; }

    [Column("D_JUMLAH", TypeName = "decimal(18, 0)")]
    public decimal? DJumlah { get; set; }

    [Column("D_HARGA", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("D_CITO", TypeName = "decimal(18, 0)")]
    public decimal? DCito { get; set; }

    [Column("D_PENYULIT", TypeName = "decimal(18, 0)")]
    public decimal? DPenyulit { get; set; }

    [Column("D_2TND", TypeName = "decimal(18, 0)")]
    public decimal? D2tnd { get; set; }

    [Column("D_ADM", TypeName = "decimal(18, 0)")]
    public decimal? DAdm { get; set; }

    [Column("D_DISKON", TypeName = "decimal(18, 0)")]
    public decimal? DDiskon { get; set; }

    [Column("D_SUBTOTAL", TypeName = "decimal(18, 0)")]
    public decimal? DSubtotal { get; set; }

    [Column("D_BEAPASIEN", TypeName = "decimal(18, 0)")]
    public decimal? DBeapasien { get; set; }

    [Column("D_BEAREKANAN", TypeName = "decimal(18, 0)")]
    public decimal? DBearekanan { get; set; }

    [Column("D_JASAMEDIS", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis { get; set; }

    [Column("D_JASAMEDIS2", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis2 { get; set; }

    [Column("D_JASAMEDIS3", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis3 { get; set; }

    [Column("D_JASAMEDIS4", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis4 { get; set; }

    [Column("D_JASAMEDIS5", TypeName = "decimal(18, 0)")]
    public decimal? DJasamedis5 { get; set; }

    [Column("D_JASARS", TypeName = "decimal(18, 0)")]
    public decimal? DJasars { get; set; }

    [Column("D_BAHANALKES", TypeName = "decimal(18, 0)")]
    public decimal? DBahanalkes { get; set; }

    [Column("V_KODETARIF")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKodetarif { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("C_APPROVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("D_APPROVE", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("V_APPROVE_VER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [Column("C_APPROVE_VER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("D_APPROVE_VER", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [ForeignKey("IdPaket")]
    [InverseProperty("TrItempakets")]
    public virtual TtPaket IdPaketNavigation { get; set; }
}