// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtAcountpasien
{
    public decimal IdAcountpasien { get; set; }

    public string IdRegistrasi { get; set; }

    public string Item { get; set; }

    public decimal? Biaya { get; set; }

    public string Paket { get; set; }

    public string Unit { get; set; }

    public decimal? Disc { get; set; }

    public string VBy { get; set; }

    public DateTime? DTgl { get; set; }

    public string CApproveVer { get; set; }

    public string VApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public int? IdStatus { get; set; }
}