// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtBetinap
{
    public decimal IdNum { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime DTglmasuk { get; set; }

    public DateTime? DTglkeluar { get; set; }

    public string VJam { get; set; }

    public string VBagian { get; set; }

    public string VRuang { get; set; }

    public string VKelas { get; set; }

    public string VNotmptidur { get; set; }

    public string VKodetarif { get; set; }

    public string VKoderuangan { get; set; }

    public string VNote { get; set; }

    public string VBy { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? CTipeaskes { get; set; }

    public string CApprove { get; set; }

    public string VApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public int? IdStatus { get; set; }

    public string VPenanggungjawab { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }
}