// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtBlacklist
{
    public decimal IdBlacklist { get; set; }

    public string IdPasien { get; set; }

    public DateTime? DTgl { get; set; }

    public string VBy { get; set; }

    public string VKeterangan { get; set; }
}