// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtDeposit
{
    public string IdRegistrasi { get; set; }

    public DateTime DTgl { get; set; }

    public decimal? DTunai { get; set; }

    public decimal? DKredit { get; set; }

    public decimal? DCharge { get; set; }

    public string VKreditnamabank { get; set; }

    public string VKreditnobatch { get; set; }

    public string VKreditnocard { get; set; }

    public string VKreditjeniscard { get; set; }

    public decimal? DTransfer { get; set; }

    public string VTransfernorekasal { get; set; }

    public string VTransfernomor { get; set; }

    public string VTransfernamabank { get; set; }

    public string VNote { get; set; }

    public string VBy { get; set; }

    public string VStatus { get; set; }

    public decimal Id { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }
}