// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Wincare.Pendaftaran.Migration.NewModel;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TTH_KUNJUNGAN")]
public partial class TthKunjungan
{
    [Column("ID_NUM", TypeName = "numeric(18, 0)")]
    public decimal IdNum { get; set; }

    [Key]
    [Column("IDKUNJUNGAN", TypeName = "numeric(18, 0)")]
    public decimal Idkunjungan { get; set; }

    [Column("IDPENGUNJUNG")]
    [StringLength(10)]
    [Unicode(false)]
    public string Idpengunjung { get; set; }

    [Column("TGLMASUK", TypeName = "datetime")]
    public DateTime? Tglmasuk { get; set; }

    [Column("TGLKELUAR", TypeName = "datetime")]
    public DateTime? Tglkeluar { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("VBY")]
    [StringLength(50)]
    [Unicode(false)]
    public string Vby { get; set; }

    [Column("KAMAR")]
    [StringLength(5)]
    [Unicode(false)]
    public string Kamar { get; set; }

    [Column("REKANANID", TypeName = "numeric(18, 0)")]
    public decimal? Rekananid { get; set; }

    [Column("ALASANBATAL")]
    [StringLength(100)]
    [Unicode(false)]
    public string Alasanbatal { get; set; }

    [ForeignKey("Idpengunjung")]
    [InverseProperty("TthKunjungans")]
    public virtual TmhPengunjung IdpengunjungNavigation { get; set; }

    [ForeignKey("Kamar")]
    [InverseProperty("TthKunjungans")]
    public virtual TmhKamar KamarNavigation { get; set; }

    [ForeignKey("Rekananid")]
    [InverseProperty("TthKunjungans")]
    public virtual TmRekanan Rekanan { get; set; }

    [InverseProperty("IdkunjunganNavigation")]
    public virtual ICollection<TthDeposit> TthDeposits { get; set; } = new List<TthDeposit>();

    [InverseProperty("IdkunjunganNavigation")]
    public virtual ICollection<TthPengunjunginap> TthPengunjunginaps { get; set; } = new List<TthPengunjunginap>();

    [InverseProperty("IdkunjunganNavigation")]
    public virtual ICollection<TthTransaksi> TthTransaksis { get; set; } = new List<TthTransaksi>();
}