// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TthPengunjunginap
{
    public decimal Idpengunjunginap { get; set; }

    public decimal Idkunjungan { get; set; }

    public DateTime? Tglmasuk { get; set; }

    public DateTime? Tglkeluar { get; set; }

    public string Kamar { get; set; }

    public string Kelas { get; set; }

    public decimal? Harga { get; set; }

    public string Status { get; set; }

    public string Vby { get; set; }

    public string VKoderuangan { get; set; }

    public virtual TthKunjungan IdkunjunganNavigation { get; set; }

    public virtual TmhKamar KamarNavigation { get; set; }
}