// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TthRubahrekananHotel
{
    public decimal IdRubahrekananhtl { get; set; }

    public DateTime? DTglrubah { get; set; }

    public string Idkunjungan { get; set; }

    public decimal? RekananidAsal { get; set; }

    public decimal? RekananidTujuan { get; set; }

    public string VKeterangan { get; set; }

    public string VBy { get; set; }
}