// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TthTransaksi
{
    public decimal Idtransaksi { get; set; }

    public decimal? Idkunjungan { get; set; }

    public DateTime? Tgltransaksi { get; set; }

    public string VGroup { get; set; }

    public string Namatransaksi { get; set; }

    public decimal? Harga { get; set; }

    public decimal? Jumlah { get; set; }

    public decimal? Diskon { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? Beapasien { get; set; }

    public decimal? Bearekanan { get; set; }

    public string Vby { get; set; }

    public int? IdStatus { get; set; }

    public virtual TthKunjungan IdkunjunganNavigation { get; set; }
}