// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtLiburdokter
{
    public decimal IdLiburdokter { get; set; }

    public string VKddokter { get; set; }

    public DateTime? TglAwal { get; set; }

    public DateTime? TglAkhir { get; set; }

    public string Keterangan { get; set; }

    public string VBy { get; set; }

    public DateTime? TglInput { get; set; }
}