// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtObatalke
{
    public decimal IdAlkes { get; set; }

    public string IdObatalkes { get; set; }

    public string IdKuitansialkes { get; set; }

    public decimal? IdBarang { get; set; }

    public string VKdobatalkes { get; set; }

    public string VNmobatalkes { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? IJml { get; set; }

    public string VNote { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? Rekananid { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public int? IdStatus { get; set; }
}