// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtObatlangsung
{
    public decimal IdObatlangsung { get; set; }

    public string VNokuitansi { get; set; }

    public DateTime? DTanggal { get; set; }

    public string VNmpembeli { get; set; }

    public string VKeterangan { get; set; }

    public string DBiaya { get; set; }

    public string IdRegistrasi { get; set; }

    public string BBayar { get; set; }

    public decimal? DJasar { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VBy { get; set; }

    public DateTime? DTglapp { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public decimal? IdRekanan { get; set; }

    public string VStatus { get; set; }

    public string VKoderequestobat { get; set; }

    public int? IdStatus { get; set; }

    public virtual ICollection<TrItemobatlangsung> TrItemobatlangsungs { get; set; } = new List<TrItemobatlangsung>();
}