// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TT_PASIENRAD")]
[Index("IdRegistrasi", "DTgldatang", "VKddokter", "IdPasienrad", "IdNum", "VBy", "VKelas", "VKoderuangan", "VNmdokter", "VUnit", "CIsdone", "IdStatus", "VKet", "IUrut", Name = "IX_TT_PASIENRAD", IsUnique = true)]
public partial class TtPasienrad
{
    [Column("ID_NUM", TypeName = "numeric(18, 0)")]
    public decimal IdNum { get; set; }

    [Required]
    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("D_TGLDATANG", TypeName = "datetime")]
    public DateTime DTgldatang { get; set; }

    [Column("V_JAM")]
    [StringLength(5)]
    [Unicode(false)]
    public string VJam { get; set; }

    [Column("I_URUT")]
    public int? IUrut { get; set; }

    [Column("C_ISDONE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CIsdone { get; set; }

    [Column("V_KODERUANGAN")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKoderuangan { get; set; }

    [Column("V_UNIT")]
    [StringLength(50)]
    [Unicode(false)]
    public string VUnit { get; set; }

    [Required]
    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("V_NMDOKTER")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmdokter { get; set; }

    [Column("V_KET")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKet { get; set; }

    [Key]
    [Column("ID_PASIENRAD")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdPasienrad { get; set; }

    [Column("V_STATUS")]
    [StringLength(50)]
    [Unicode(false)]
    public string VStatus { get; set; }

    [Column("V_KELAS")]
    [StringLength(50)]
    [Unicode(false)]
    public string VKelas { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("C_APPROVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("D_APPROVE", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("V_APPROVE_ANA")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveAna { get; set; }

    [Column("C_APPROVE_ANA")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveAna { get; set; }

    [Column("D_APPROVE_ANA", TypeName = "datetime")]
    public DateTime? DApproveAna { get; set; }

    [Column("V_APPROVE_VER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [Column("C_APPROVE_VER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("D_APPROVE_VER", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [Column("V_KETKLINIK")]
    [StringLength(50)]
    [Unicode(false)]
    public string VKetklinik { get; set; }

    [Column("V_PENGOBATAN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VPengobatan { get; set; }

    [Column("V_KETBAHAN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VKetbahan { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [ForeignKey("IdRegistrasi")]
    [InverseProperty("TtPasienrads")]
    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }

    [InverseProperty("IdPasienradNavigation")]
    public virtual ICollection<TrHasilrad> TrHasilrads { get; set; } = new List<TrHasilrad>();

    [ForeignKey("VKddokter")]
    [InverseProperty("TtPasienrads")]
    public virtual TmDokter VKddokterNavigation { get; set; }

    [ForeignKey("VKoderuangan")]
    [InverseProperty("TtPasienrads")]
    public virtual TmRuang VKoderuanganNavigation { get; set; }
}