// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPasienrad
{
    public decimal IdNum { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime DTgldatang { get; set; }

    public string VJam { get; set; }

    public int? IUrut { get; set; }

    public string CIsdone { get; set; }

    public string VKoderuangan { get; set; }

    public string VUnit { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VKet { get; set; }

    public string IdPasienrad { get; set; }

    public string VStatus { get; set; }

    public string VKelas { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveAna { get; set; }

    public string CApproveAna { get; set; }

    public DateTime? DApproveAna { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public string VKetklinik { get; set; }

    public string VPengobatan { get; set; }

    public string VKetbahan { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }

    public virtual ICollection<TrHasilrad> TrHasilrads { get; set; } = new List<TrHasilrad>();

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}