// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPasienRencanaRad
{
    public decimal IdRencanakegiatan { get; set; }

    public DateTime? DTgl { get; set; }

    public string VJam { get; set; }

    public string IdPasien { get; set; }

    public string VNamapasien { get; set; }

    public string VTelepon { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VKelompok { get; set; }

    public string VKegiatan { get; set; }

    public string CStatus { get; set; }

    public string VBy { get; set; }

    public virtual TmPasien IdPasienNavigation { get; set; }
}