// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPasieninap
{
    public decimal IdNum { get; set; }

    public string IdRegistrasi { get; set; }

    public string IdPasieninap { get; set; }

    public DateTime? DTgldatang { get; set; }

    public string VJamdatang { get; set; }

    public string VKddokter { get; set; }

    public string VCaramasuk { get; set; }

    public string VKdpengirim { get; set; }

    public string VNmpengirim { get; set; }

    public string VTipepengirim { get; set; }

    public string VKeluhan { get; set; }

    public string VKeteranganawal { get; set; }

    public string VNmpenjamin { get; set; }

    public string VAlamatpenjamin { get; set; }

    public string VTelppenjamin { get; set; }

    public bool? BJaminpribadi { get; set; }

    public DateTime? DTglpulang { get; set; }

    public string VJampulang { get; set; }

    public string VCarakeluar { get; set; }

    public string VKeadaanakhir { get; set; }

    public string VBy { get; set; }

    public string CIsdone { get; set; }

    public string Note { get; set; }

    public string Dokter1 { get; set; }

    public string Dokter2 { get; set; }

    public string Dokter3 { get; set; }

    public string Dokter4 { get; set; }

    public string Dokter5 { get; set; }

    public string VKoderuangan { get; set; }

    public int? IdStatus { get; set; }

    public string VHakkelas { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}