// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TT_PAIDOUT")]
[Index("IdPaidout", Name = "IX_TT_PAIDOUT")]
[Index("DTgl", Name = "IX_TT_PAIDOUT_1")]
[Index("IdStatus", Name = "IX_TT_PAIDOUT_2")]
[Index("DJumlah", Name = "IX_TT_PAIDOUT_3")]
[Index("VCarabayar", Name = "IX_TT_PAIDOUT_4")]
public partial class TtPaidout
{
    [Key]
    [Column("ID_PAIDOUT", TypeName = "numeric(18, 0)")]
    public decimal IdPaidout { get; set; }

    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("ID_PASIEN")]
    [StringLength(10)]
    [Unicode(false)]
    public string IdPasien { get; set; }

    [Column("V_NAMAPASIEN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNamapasien { get; set; }

    [Column("D_TGL", TypeName = "datetime")]
    public DateTime? DTgl { get; set; }

    [Column("D_JUMLAH", TypeName = "decimal(18, 0)")]
    public decimal? DJumlah { get; set; }

    [Column("V_CARABAYAR")]
    [StringLength(50)]
    [Unicode(false)]
    public string VCarabayar { get; set; }

    [Column("V_NOTEBAYAR")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNotebayar { get; set; }

    [Column("V_KETERANGAN")]
    [StringLength(500)]
    [Unicode(false)]
    public string VKeterangan { get; set; }

    [Column("V_APPROVEDBY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApprovedby { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [ForeignKey("IdRegistrasi")]
    [InverseProperty("TtPaidouts")]
    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }
}