// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPaket
{
    public decimal IdPaket { get; set; }

    public string VNomorpaket { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTgl { get; set; }

    public decimal? IdMasterpemeriksaanpenunjang { get; set; }

    public string VKdpemeriksaan { get; set; }

    public string VNmpemeriksaan { get; set; }

    public string VKoderuangan { get; set; }

    public string VNmunit { get; set; }

    public string VKodetarif { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public decimal? IdRekanan { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DDiskon { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public int? IdStatus { get; set; }

    public string VApprove { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }

    public virtual ICollection<TrItempaket> TrItempakets { get; set; } = new List<TrItempaket>();
}