// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPaketPbAppDetail
{
    public decimal IdPaketpbAppdetail { get; set; }

    public decimal? IdPaketpbApp { get; set; }

    public decimal? IdBarang { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DJmlapp { get; set; }

    public string VByapp { get; set; }

    public int? IdStatus { get; set; }
}