// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPenjadwalan
{
    public decimal IdPenjadwalan { get; set; }

    public string IdPasien { get; set; }

    public string VNamaPasien { get; set; }

    public string VAlamatPasien { get; set; }

    public string VTelpPasien { get; set; }

    public string VKddokter { get; set; }

    public string VKoderuangan { get; set; }

    public DateTime? DTglJadwal { get; set; }

    public int? IUrut { get; set; }

    public string VJam { get; set; }

    public decimal? IdJadwal { get; set; }

    public DateTime? DTglInput { get; set; }

    public string VBy { get; set; }

    public string VStatus { get; set; }

    public string VKet { get; set; }

    public virtual TmPasien IdPasienNavigation { get; set; }
}