// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPemeriksaanradiologi
{
    public decimal IdNumpasienrad { get; set; }

    public string IdPasienrad { get; set; }

    public string VKdrad { get; set; }

    public string VNmpemeriksaanrad { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DCito { get; set; }

    public decimal? DPenyulit { get; set; }

    public decimal? D2tnd { get; set; }

    public decimal? DAdm { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DSubtotal { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DJasabaca { get; set; }

    public decimal? DJasapengirim { get; set; }

    public decimal? DJasars { get; set; }

    public decimal? DBahanalkes { get; set; }

    public string VKelompok { get; set; }

    public string VBy { get; set; }

    public string VApprove { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveAna { get; set; }

    public string CApproveAna { get; set; }

    public DateTime? DApproveAna { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public string VKelas { get; set; }

    public int? IdStatus { get; set; }
}