// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pendaftaran.Migration.Models;

public partial class TtPlafonbpj
{
    public decimal Idbpjs { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTgl { get; set; }

    public decimal? DBpjs { get; set; }

    public string VKeterangan { get; set; }

    public string VBy { get; set; }

    public string VStatus { get; set; }

    public int? IdStatus { get; set; }
}