// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TTH_RUBAHREKANAN_HOTEL")]
public partial class TthRubahrekananHotel
{
    [Key]
    [Column("ID_RUBAHREKANANHTL", TypeName = "numeric(18, 0)")]
    public decimal IdRubahrekananhtl { get; set; }

    [Column("D_TGLRUBAH", TypeName = "datetime")]
    public DateTime? DTglrubah { get; set; }

    [Column("IDKUNJUNGAN")]
    [StringLength(12)]
    [Unicode(false)]
    public string Idkunjungan { get; set; }

    [Column("REKANANID_ASAL", TypeName = "numeric(18, 0)")]
    public decimal? RekananidAsal { get; set; }

    [Column("REKANANID_TUJUAN", TypeName = "numeric(18, 0)")]
    public decimal? RekananidTujuan { get; set; }

    [Column("V_KETERANGAN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VKeterangan { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }
}