// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("D_Gudang")]
[Index("Request", Name = "IX_GUDANG_ISREQUEST")]
[Index("Aktif", Name = "IX_GUDANG_IS_AKTIF")]
[Index("KodeInventory", Name = "IX_GUDANG_KDINV")]
[Index("Listropp", Name = "IX_GUDANG_LISROP")]
[Index("NamaGudangObat", Name = "IX_GUDANG_NAMAGUDANG")]
public partial class TmGudang
{
    [Column("IdGudangObat", TypeName = "numeric(18, 0)")]
    public decimal IdGudangobat { get; set; }

    [Key]
    [Column("KodeInventory")]
    [StringLength(2)]
    [Unicode(false)]
    public string Kodeinventory { get; set; }

    [Column("NamaGudangObat")]
    [StringLength(50)]
    [Unicode(false)]
    public string NamaGudangObat { get; set; }

    [Column("Aktif")]
    public bool? Aktif { get; set; }

    [Column("Request")]
    public bool? Request { get; set; }

    [Column("Listropp")]
    public bool? Listropp { get; set; }

    [Column("TipeBarang")]
    [StringLength(1)]
    [Unicode(false)]
    public string TipeBarang { get; set; }

    [Column("Paketbhp")]
    public bool? Paketbhp { get; set; }

    [Column("Returbhp")]
    public bool? Returbhp { get; set; }

    [InverseProperty("KodeRequestobatNavigation")]
    public virtual ICollection<TmRuang> TmRuangKodeRequestobatNavigations { get; set; } = new List<TmRuang>();

    [InverseProperty("VKodeinventoryNavigation")]
    public virtual ICollection<TmRuang> TmRuangVKodeinventoryNavigations { get; set; } = new List<TmRuang>();

    [InverseProperty("VKodeinventoryNavigation")]
    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    [InverseProperty("VKoderequestobatNavigation")]
    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();
}