// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("D_PembayaranLock")]
public partial class D_PembayaranLock
{
    [Key]
    [Column("IdLockBayar", TypeName = "numeric(18, 0)")]
    public decimal IdLockBayar { get; set; }

    [Column("IdRegistrasi")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("LockUnlock")]
    public bool? LockUnlock { get; set; }
}