// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("D_Ruang")]
[Index("KodeRuangan", Name = "IX_RUANG")]
[Index("Nama", Name = "IX_RUANG_1")]
[Index("Kamar", Name = "IX_RUANG_2")]
[Index("KodeInventory", Name = "IX_RUANG_3")]
[Index("KodeRequestobat", Name = "IX_RUANG_4")]
[Index("KodeTarif", Name = "IX_RUANG_5")]
[Index("Aktif", Name = "IX_RUANG_6")]
[Index("IdNumRuang", Name = "IX_RUANG_7")]
[Index("KdInhealth", Name = "IX_KDINHEALTH")]
[Index("LynInhealth", Name = "IX_LYNINHEALTH")]
public partial class D_Ruang
{
    [Column("IdNumRuang", TypeName = "numeric(18, 0)")]
    public decimal IdNumRuang { get; set; }

    [Key]
    [Column("KodeRuangan")]
    [StringLength(5)]
    [Unicode(false)]
    public string KodeRuangan { get; set; }

    [Required]
    [Column("Nama")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nama { get; set; }

    [Column("NoRuang")]
    [StringLength(10)]
    [Unicode(false)]
    public string NoRuang { get; set; }

    [Column("Kelompok")]
    [StringLength(1)]
    [Unicode(false)]
    public string Kelompok { get; set; }

    [Column("Kamar")]
    [StringLength(10)]
    [Unicode(false)]
    public string Kamar { get; set; }

    [Column("KodeInventory")]
    [StringLength(2)]
    [Unicode(false)]
    public string KodeInventory { get; set; }

    [Column("KodeRequestObat")]
    [StringLength(2)]
    [Unicode(false)]
    public string KodeRequestObat { get; set; }

    [Column("KodeTarif")]
    [StringLength(2)]
    [Unicode(false)]
    public string KodeTarif { get; set; }

    [Column("Aktif")]
    public bool? Aktif { get; set; }

    [Column("IsTarif")]
    public bool? IsTarif { get; set; }

    [Column("Gdgpaket")]
    [StringLength(2)]
    [Unicode(false)]
    public string Gdgpaket { get; set; }

    [Column("GdgRetur")]
    [StringLength(2)]
    [Unicode(false)]
    public string GdgRetur { get; set; }

    [Column("GdgPenerimaan")]
    [StringLength(2)]
    [Unicode(false)]
    public string GdgPenerimaan { get; set; }

    [Column("KdInhealth")]
    [StringLength(3)]
    [Unicode(false)]
    public string KdInhealth { get; set; }

    [Column("LynInhealth")]
    [StringLength(50)]
    [Unicode(false)]
    public string LynInhealth { get; set; }

    [ForeignKey("KodeRequestObat")]
    [InverseProperty("TmRuangKodeRequestobatNavigations")]
    public virtual D_Gudang KodeRequestObatNavigation { get; set; }

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TmJadwaldokter> TmJadwaldokters { get; set; } = new List<TmJadwaldokter>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasieninap> TtPasieninaps { get; set; } = new List<TtPasieninap>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienlab> TtPasienlabs { get; set; } = new List<TtPasienlab>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienpenunjang> TtPasienpenunjangs { get; set; } = new List<TtPasienpenunjang>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienrad> TtPasienrads { get; set; } = new List<TtPasienrad>();

    [InverseProperty("VKoderuanganNavigation")]
    public virtual ICollection<TtPasienugd> TtPasienugds { get; set; } = new List<TtPasienugd>();

    [ForeignKey("KodeInventory")]
    [InverseProperty("TmRuangVKodeinventoryNavigations")]
    public virtual D_Gudang KodeInventoryNavigation { get; set; }
}