// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("D_TarifRekananSub")]
public partial class D_TarifRekananSub
{
    [Key]
    [Column("IdTarifRekananSub", TypeName = "numeric(18, 0)")]
    public decimal IdTarifRekananSub { get; set; }

    [Column("RekananIdHd", TypeName = "numeric(18, 0)")]
    public decimal RekananIdHd { get; set; }

    [Column("RekananIdDt", TypeName = "numeric(18, 0)")]
    public decimal RekananIdDt { get; set; }
}