// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TM_SETTING_DAFTAR")]
public partial class TmSettingDaftar
{
    [Column("ID_SETTINGDAFTAR", TypeName = "numeric(18, 0)")]
    public decimal IdSettingdaftar { get; set; }

    [Column("V_NMUNITDAFTAR")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNmunitdaftar { get; set; }

    [Column("V_KODERUANGAN")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKoderuangan { get; set; }

    [Key]
    [Column("V_TUJUAN")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTujuan { get; set; }

    [Column("IS_TAMPIL")]
    public bool? IsTampil { get; set; }
}