// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TM_TARIF_GROUP")]
public partial class TmTarifGroup
{
    [Key]
    [Column("ID_GROUPTARIF", TypeName = "numeric(18, 0)")]
    public decimal IdGrouptarif { get; set; }

    [Column("V_NMGROUPTARIF")]
    [StringLength(20)]
    [Unicode(false)]
    public string VNmgrouptarif { get; set; }

    [Column("V_ALIASGROUP")]
    [StringLength(3)]
    [Unicode(false)]
    public string VAliasgroup { get; set; }

    [Column("V_KDAKUN")]
    [StringLength(8)]
    [Unicode(false)]
    public string VKdakun { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [InverseProperty("IdGrouptarifNavigation")]
    public virtual ICollection<TmTarifdetail> TmTarifdetails { get; set; } = new List<TmTarifdetail>();
}