// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TR_ITEMNONMEDIS")]
public partial class TrItemnonmedi
{
    [Key]
    [Column("ID_ITEMNONMEDIS", TypeName = "numeric(18, 0)")]
    public decimal IdItemnonmedis { get; set; }

    [Column("ID_TRANSAKSINONMEDIS", TypeName = "numeric(18, 0)")]
    public decimal? IdTransaksinonmedis { get; set; }

    [Required]
    [Column("V_KDTARIF")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdtarif { get; set; }

    [Column("V_NMTARIF")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNmtarif { get; set; }

    [Column("V_GROUP")]
    [StringLength(50)]
    [Unicode(false)]
    public string VGroup { get; set; }

    [Column("D_HARGA", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("D_JUMLAH", TypeName = "decimal(18, 0)")]
    public decimal? DJumlah { get; set; }

    [Column("D_DISKON", TypeName = "decimal(18, 0)")]
    public decimal? DDiskon { get; set; }

    [Column("D_SUBTOTAL", TypeName = "decimal(18, 0)")]
    public decimal? DSubtotal { get; set; }

    [Column("D_BEAPASIEN", TypeName = "decimal(18, 0)")]
    public decimal? DBeapasien { get; set; }

    [Column("D_BEAREKANAN", TypeName = "decimal(18, 0)")]
    public decimal? DBearekanan { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [ForeignKey("IdTransaksinonmedis")]
    [InverseProperty("TrItemnonmedis")]
    public virtual TtTransaksinonmedi IdTransaksinonmedisNavigation { get; set; }
}