// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TT_LIBURDOKTER")]
public partial class TtLiburdokter
{
    [Key]
    [Column("ID_LIBURDOKTER", TypeName = "numeric(18, 0)")]
    public decimal IdLiburdokter { get; set; }

    [Required]
    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("TGL_AWAL", TypeName = "datetime")]
    public DateTime? TglAwal { get; set; }

    [Column("TGL_AKHIR", TypeName = "datetime")]
    public DateTime? TglAkhir { get; set; }

    [Column("KETERANGAN")]
    [StringLength(500)]
    [Unicode(false)]
    public string Keterangan { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("TGL_INPUT", TypeName = "datetime")]
    public DateTime? TglInput { get; set; }
}