// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pendaftaran.Migration.Models;

[Table("TT_TRANSAKSINONMEDIS")]
[Index("IdTransaksinonmedis", Name = "IX_TT_TRANSAKSINONMEDIS")]
[Index("DTgl", Name = "IX_TT_TRANSAKSINONMEDIS_1")]
[Index("DBayartransfer", Name = "IX_TT_TRANSAKSINONMEDIS_10")]
[Index("IdStatus", Name = "IX_TT_TRANSAKSINONMEDIS_11")]
[Index("VStatus", Name = "IX_TT_TRANSAKSINONMEDIS_12")]
[Index("VNokuitansi", Name = "IX_TT_TRANSAKSINONMEDIS_2")]
[Index("IdPasien", Name = "IX_TT_TRANSAKSINONMEDIS_3")]
[Index("VNmpembeli", Name = "IX_TT_TRANSAKSINONMEDIS_4")]
[Index("VKeterangan", Name = "IX_TT_TRANSAKSINONMEDIS_5")]
[Index("Rekananid", Name = "IX_TT_TRANSAKSINONMEDIS_6")]
[Index("DBayartunai", Name = "IX_TT_TRANSAKSINONMEDIS_7")]
[Index("DBayarkredit", Name = "IX_TT_TRANSAKSINONMEDIS_8")]
[Index("DCharge", Name = "IX_TT_TRANSAKSINONMEDIS_9")]
public partial class TtTransaksinonmedi
{
    [Key]
    [Column("ID_TRANSAKSINONMEDIS", TypeName = "numeric(18, 0)")]
    public decimal IdTransaksinonmedis { get; set; }

    [Column("D_TGL", TypeName = "datetime")]
    public DateTime? DTgl { get; set; }

    [Column("V_NOKUITANSI")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNokuitansi { get; set; }

    [Column("ID_PASIEN")]
    [StringLength(10)]
    [Unicode(false)]
    public string IdPasien { get; set; }

    [Column("V_NMPEMBELI")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmpembeli { get; set; }

    [Column("V_KETERANGAN")]
    [StringLength(300)]
    [Unicode(false)]
    public string VKeterangan { get; set; }

    [Column("D_TOTAL", TypeName = "decimal(18, 0)")]
    public decimal? DTotal { get; set; }

    [Column("D_BAYARTUNAI", TypeName = "decimal(18, 0)")]
    public decimal? DBayartunai { get; set; }

    [Column("D_BAYARKREDIT", TypeName = "decimal(18, 0)")]
    public decimal? DBayarkredit { get; set; }

    [Column("D_CHARGE", TypeName = "decimal(18, 0)")]
    public decimal? DCharge { get; set; }

    [Column("V_KREDITNAMABANK")]
    [StringLength(100)]
    [Unicode(false)]
    public string VKreditnamabank { get; set; }

    [Column("V_KREDITNOBATCH")]
    [StringLength(100)]
    [Unicode(false)]
    public string VKreditnobatch { get; set; }

    [Column("V_KREDITNOCARD")]
    [StringLength(100)]
    [Unicode(false)]
    public string VKreditnocard { get; set; }

    [Column("V_KREDITJENISCARD")]
    [StringLength(100)]
    [Unicode(false)]
    public string VKreditjeniscard { get; set; }

    [Column("D_BAYARTRANSFER", TypeName = "decimal(18, 0)")]
    public decimal? DBayartransfer { get; set; }

    [Column("V_TRANSFERNOREKASAL")]
    [StringLength(100)]
    [Unicode(false)]
    public string VTransfernorekasal { get; set; }

    [Column("V_TRANSFERNOMOR")]
    [StringLength(100)]
    [Unicode(false)]
    public string VTransfernomor { get; set; }

    [Column("V_TRANSFERNAMABANK")]
    [StringLength(100)]
    [Unicode(false)]
    public string VTransfernamabank { get; set; }

    [Column("D_COMPLIMENT", TypeName = "decimal(18, 0)")]
    public decimal? DCompliment { get; set; }

    [Column("D_ASURANSI", TypeName = "decimal(18, 0)")]
    public decimal? DAsuransi { get; set; }

    [Column("D_PERJANJIAN", TypeName = "decimal(18, 0)")]
    public decimal? DPerjanjian { get; set; }

    [Column("D_KEMBALI", TypeName = "decimal(18, 0)")]
    public decimal? DKembali { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("V_STATUS")]
    [StringLength(50)]
    [Unicode(false)]
    public string VStatus { get; set; }

    [Column("REKANANID", TypeName = "numeric(18, 0)")]
    public decimal? Rekananid { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [InverseProperty("IdTransaksinonmedisNavigation")]
    public virtual ICollection<TrItemnonmedi> TrItemnonmedis { get; set; } = new List<TrItemnonmedi>();
}