// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class LisHasil
{
    public string IdPasienlab { get; set; }

    public int? NoUrut { get; set; }

    public string KodeTest { get; set; }

    public string NmTest { get; set; }

    public string Hasil { get; set; }

    public string Unit { get; set; }

    public string Normal { get; set; }

    public string Flag { get; set; }

    public string Type { get; set; }

    public decimal Idn { get; set; }
}