// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmAsal
{
    public decimal IdAsal { get; set; }

    public decimal? IdAsalgroup { get; set; }

    public string VKdasal { get; set; }

    public string VNmasal { get; set; }

    public bool IsAktif { get; set; }

    public virtual ICollection<TtPasienpd> TtPasienpds { get; set; } = new List<TtPasienpd>();

    public virtual ICollection<TtPasienugd> TtPasienugds { get; set; } = new List<TtPasienugd>();
}