// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmAturanpakai
{
    public decimal IdAturanpakai { get; set; }

    public string VKdaturanpakai { get; set; }

    public string VNmaturanpakai { get; set; }

    public string VKetaturanpakai { get; set; }

    public bool? IsAktif { get; set; }
}