// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmDiagnosa
{
    public decimal IdDiagnosa { get; set; }

    public string VKddiagnosa { get; set; }

    public string VNmdiagnosa { get; set; }

    public bool? CIspenyakit { get; set; }

    public string VKddtd { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmMorfologi> TmMorfologis { get; set; } = new List<TmMorfologi>();
}