// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmDokterHonor
{
    public decimal Id { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public decimal? DTarif { get; set; }

    public decimal? DJasamedis { get; set; }

    public decimal? DJasars { get; set; }

    public string VKet { get; set; }
}