// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmDtd
{
    public decimal IdDtd { get; set; }

    public string VKddtd { get; set; }

    public string VNmdtd { get; set; }

    public bool? IsAktif { get; set; }
}