// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmFarmakoterapi
{
    public decimal IdFarmakoterapi { get; set; }

    public string VNmfarmakoterapi { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmFarmakoterapiSub> TmFarmakoterapiSubs { get; set; } = new List<TmFarmakoterapiSub>();
}