// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmGudang
{
    public decimal IdGudangobat { get; set; }

    public string VKodeinventory { get; set; }

    public string VNamagudangobat { get; set; }

    public bool? IsAktif { get; set; }

    public bool? IsRequest { get; set; }

    public bool? IsListropp { get; set; }

    public string IsTipebarang { get; set; }

    public bool? IsPaketbhp { get; set; }

    public bool? IsReturbhp { get; set; }

    public virtual ICollection<TmRuang> TmRuangKodeRequestobatNavigations { get; set; } = new List<TmRuang>();

    public virtual ICollection<TmRuang> TmRuangVKodeinventoryNavigations { get; set; } = new List<TmRuang>();

    public virtual ICollection<TtHistoryStok> TtHistoryStoks { get; set; } = new List<TtHistoryStok>();

    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();

    public virtual ICollection<TtPaketPbApp> TtPaketPbAppVKodetarifNavigations { get; set; } = new List<TtPaketPbApp>();

    public virtual ICollection<TtPaketPbApp> TtPaketPbAppVKodetarifgdgNavigations { get; set; } = new List<TtPaketPbApp>();

    public virtual ICollection<TtPaketPbPakai> TtPaketPbPakais { get; set; } = new List<TtPaketPbPakai>();

    public virtual ICollection<TtPaketPbRetur> TtPaketPbReturVKodetarifNavigations { get; set; } = new List<TtPaketPbRetur>();

    public virtual ICollection<TtPaketPbRetur> TtPaketPbReturVKodetarifgdgNavigations { get; set; } = new List<TtPaketPbRetur>();

    public virtual ICollection<TtReturApp> TtReturApps { get; set; } = new List<TtReturApp>();

    public virtual ICollection<TtReturDist> TtReturDists { get; set; } = new List<TtReturDist>();
}