// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmHargabarang
{
    public decimal Idhargabeli { get; set; }

    public decimal? Barangid { get; set; }

    public decimal? Supplierid { get; set; }

    public DateTime? Lastupdate { get; set; }

    public decimal? Harga { get; set; }

    public string Inputby { get; set; }

    public decimal? Diskonon { get; set; }

    public decimal? Diskonoff { get; set; }

    public decimal? Ppn { get; set; }

    public bool? IsAktif { get; set; }
}