// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmJadwaldokter
{
    public decimal IdJadwal { get; set; }

    public string VKddokter { get; set; }

    public string VHari { get; set; }

    public string VJamstart { get; set; }

    public string VJamfinish { get; set; }

    public string VKoderuangan { get; set; }

    public string VNamaklinik { get; set; }

    public int? IServistime { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TtPasienpd> TtPasienpds { get; set; } = new List<TtPasienpd>();

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}