// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmMorfologi
{
    public decimal IdMorfologi { get; set; }

    public string VKdmorfologi { get; set; }

    public string VNmmorfologi { get; set; }

    public string VKddiagnosa { get; set; }

    public bool? IsAktif { get; set; }

    public virtual TmDiagnosa VKddiagnosaNavigation { get; set; }
}