// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmObatunit
{
    public decimal IdObatunit { get; set; }

    public decimal? Barangid { get; set; }

    public string VKdobat { get; set; }

    public string VNmobat { get; set; }

    public string VKodeinventory { get; set; }

    public DateTime? DExpireddate { get; set; }

    public decimal? DStokmin { get; set; }

    public decimal? DStokmax { get; set; }

    public decimal? DStoknow { get; set; }

    public bool? VRod { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }
}