// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmPaketHarga
{
    public decimal IdPaketkelas { get; set; }

    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    public decimal? IdPenunjangdetail { get; set; }

    public decimal Rekananid { get; set; }

    public string VKelas { get; set; }

    public decimal? DJumlah { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DCito { get; set; }

    public decimal? DPenyulit { get; set; }

    public decimal? D2tnd { get; set; }

    public decimal? DAdm { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DSubtotal { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DJasamedis { get; set; }

    public decimal? DJasamedis2 { get; set; }

    public decimal? DJasamedis3 { get; set; }

    public decimal? DJasamedis4 { get; set; }

    public decimal? DJasamedis5 { get; set; }

    public decimal? DJasars { get; set; }

    public decimal? DBahanalkes { get; set; }

    public DateTime? DTglawal { get; set; }

    public DateTime? DTglakhir { get; set; }

    public DateTime? DLastupdate { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }
}