// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TM_PAKETDETAIL")]
public partial class TmPaketdetail
{
    [Key]
    [Column("ID_PAKETDETAIL", TypeName = "numeric(18, 0)")]
    public decimal IdPaketdetail { get; set; }

    [Column("V_KDPAKETDETAIL")]
    [StringLength(50)]
    [Unicode(false)]
    public string VKdpaketdetail { get; set; }

    [Column("V_NMPAKETDETAIL")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNmpaketdetail { get; set; }

    [Column("V_GROUP")]
    [StringLength(50)]
    [Unicode(false)]
    public string VGroup { get; set; }

    [Column("V_TIPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string VTipe { get; set; }

    [Column("D_HARGA", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("REKANAN")]
    [StringLength(50)]
    [Unicode(false)]
    public string Rekanan { get; set; }
}