// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmPaketRekanan
{
    public decimal IdPaketrekanan { get; set; }

    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    public decimal Rekananid { get; set; }

    public bool? IsAktif { get; set; }
}