// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TM_PEMERIKSAANPENUNJANG")]
public partial class TmPemeriksaanpenunjang
{
    [Key]
    [Column("ID_MASTERPEMERIKSAANPENUNJANG", TypeName = "numeric(18, 0)")]
    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    [Required]
    [Column("V_KDPEMERIKSAAN")]
    [StringLength(8)]
    [Unicode(false)]
    public string VKdpemeriksaan { get; set; }

    [Column("V_NMPEMERIKSAAN")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmpemeriksaan { get; set; }

    [Column("D_HARGA", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("D_BEAPASIEN", TypeName = "decimal(18, 0)")]
    public decimal? DBeapasien { get; set; }

    [Column("D_BEAREKANAN", TypeName = "decimal(18, 0)")]
    public decimal? DBearekanan { get; set; }

    [Column("V_PENUNJANG")]
    [StringLength(20)]
    [Unicode(false)]
    public string VPenunjang { get; set; }

    [Column("REKANANID", TypeName = "numeric(18, 0)")]
    public decimal Rekananid { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [Column("ID_GROUPTARIF", TypeName = "numeric(18, 0)")]
    public decimal? IdGrouptarif { get; set; }

    [InverseProperty("IdMasterpemeriksaanpenunjangNavigation")]
    public virtual ICollection<TmPemeriksaanpenunjangdetail> TmPemeriksaanpenunjangdetails { get; set; } = new List<TmPemeriksaanpenunjangdetail>();

    [InverseProperty("IdMasterpemeriksaanpenunjangNavigation")]
    public virtual ICollection<TtPaket> TtPakets { get; set; } = new List<TtPaket>();
}