// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmPemeriksaanpenunjang
{
    public decimal IdMasterpemeriksaanpenunjang { get; set; }

    public string VKdpemeriksaan { get; set; }

    public string VNmpemeriksaan { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public string VPenunjang { get; set; }

    public decimal Rekananid { get; set; }

    public string VBy { get; set; }

    public bool? IsAktif { get; set; }

    public decimal? IdGrouptarif { get; set; }

    public virtual ICollection<TmPemeriksaanpenunjangdetail> TmPemeriksaanpenunjangdetails { get; set; } = new List<TmPemeriksaanpenunjangdetail>();

    public virtual ICollection<TtPaket> TtPakets { get; set; } = new List<TtPaket>();
}