// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmRekanan
{
    public decimal IdNumrekanan { get; set; }

    public decimal Rekananid { get; set; }

    public string VNmrekanan { get; set; }

    public string VAlamat { get; set; }

    public string VKota { get; set; }

    public string VTelp { get; set; }

    public string VAlias { get; set; }

    public bool? IsAktif { get; set; }

    public string VKdakun { get; set; }

    public bool? IsPaketbhp { get; set; }

    public bool? IsTarif { get; set; }

    public bool? IsTarifnonmed { get; set; }

    public bool? IsCob { get; set; }

    public virtual ICollection<TmPasien> TmPasiens { get; set; } = new List<TmPasien>();

    public virtual ICollection<TtKunjungan> TtKunjungans { get; set; } = new List<TtKunjungan>();

    public virtual ICollection<TtPaketPbPakai> TtPaketPbPakais { get; set; } = new List<TtPaketPbPakai>();

    public virtual ICollection<TtPaketPbRetur> TtPaketPbReturs { get; set; } = new List<TtPaketPbRetur>();
}