// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmStatus
{
    public int IdStatus { get; set; }

    public string VStatus { get; set; }

    public virtual ICollection<TrItemobatlangsung> TrItemobatlangsungs { get; set; } = new List<TrItemobatlangsung>();

    public virtual ICollection<TrItempaket> TrItempakets { get; set; } = new List<TrItempaket>();

    public virtual ICollection<TtDiagnosaDetail> TtDiagnosaDetails { get; set; } = new List<TtDiagnosaDetail>();

    public virtual ICollection<TtKuitansialke> TtKuitansialkes { get; set; } = new List<TtKuitansialke>();

    public virtual ICollection<TtKuitansiresep> TtKuitansireseps { get; set; } = new List<TtKuitansiresep>();

    public virtual ICollection<TtKunjungan> TtKunjungans { get; set; } = new List<TtKunjungan>();

    public virtual ICollection<TtObatalke> TtObatalkes { get; set; } = new List<TtObatalke>();

    public virtual ICollection<TtObatlangsung> TtObatlangsungs { get; set; } = new List<TtObatlangsung>();

    public virtual ICollection<TtPaket> TtPakets { get; set; } = new List<TtPaket>();

    public virtual ICollection<TtPasienpd> TtPasienpds { get; set; } = new List<TtPasienpd>();

    public virtual ICollection<TtPasienpenunjang> TtPasienpenunjangs { get; set; } = new List<TtPasienpenunjang>();

    public virtual ICollection<TtPasienugd> TtPasienugds { get; set; } = new List<TtPasienugd>();

    public virtual ICollection<TtPembayaranDetail> TtPembayaranDetails { get; set; } = new List<TtPembayaranDetail>();

    public virtual ICollection<TtRetur> TtReturs { get; set; } = new List<TtRetur>();

    public virtual ICollection<TtTindakan> TtTindakans { get; set; } = new List<TtTindakan>();
}