// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmTarifRekanan
{
    public decimal IdTarifrekanan { get; set; }

    public string VKdtarifdetail { get; set; }

    public decimal Rekananid { get; set; }

    public bool? IsAktif { get; set; }
}