// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmTarifGroup
{
    public decimal IdGrouptarif { get; set; }

    public string VNmgrouptarif { get; set; }

    public string VAliasgroup { get; set; }

    public string VKdakun { get; set; }

    public bool? IsAktif { get; set; }

    public virtual ICollection<TmTarifdetail> TmTarifdetails { get; set; } = new List<TmTarifdetail>();
}