// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TM_TARIFDETAIL")]
public partial class TmTarifdetail
{
    [Column("ID_TARIFDETAIL", TypeName = "numeric(18, 0)")]
    public decimal IdTarifdetail { get; set; }

    [Column("V_KODETARIFLAYAN")]
    [StringLength(2)]
    [Unicode(false)]
    public string VKodetariflayan { get; set; }

    [Key]
    [Column("V_KDTARIFDETAIL")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdtarifdetail { get; set; }

    [Required]
    [Column("V_NMTARIFDETAIL")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmtarifdetail { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [Column("ID_GROUPTARIF", TypeName = "numeric(18, 0)")]
    public decimal? IdGrouptarif { get; set; }

    [ForeignKey("IdGrouptarif")]
    [InverseProperty("TmTarifdetails")]
    public virtual TmTarifGroup IdGrouptarifNavigation { get; set; }

    [ForeignKey("VKodetariflayan")]
    [InverseProperty("TmTarifdetails")]
    public virtual TmTarifPelayanan VKodetariflayanNavigation { get; set; }
}