// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TmTindakan
{
    public decimal IdTindakan { get; set; }

    public string VKdtindakan { get; set; }

    public string VNmtindakan { get; set; }

    public string VNmpendek { get; set; }

    public bool? IsAktif { get; set; }
}