// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrItempaket
{
    public decimal IdDetailpaket { get; set; }

    public decimal? IdPaket { get; set; }

    public string VNomorpaket { get; set; }

    public decimal? IdMasterpemeriksaanpenunjang { get; set; }

    public decimal? IdPenunjangdetail { get; set; }

    public string VKddetail { get; set; }

    public string VNmdetail { get; set; }

    public string VGroup { get; set; }

    public string VTipe { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public decimal? DJumlah { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DCito { get; set; }

    public decimal? DPenyulit { get; set; }

    public decimal? D2tnd { get; set; }

    public decimal? DAdm { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DSubtotal { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DJasamedis { get; set; }

    public decimal? DJasamedis2 { get; set; }

    public decimal? DJasamedis3 { get; set; }

    public decimal? DJasamedis4 { get; set; }

    public decimal? DJasamedis5 { get; set; }

    public decimal? DJasars { get; set; }

    public decimal? DBahanalkes { get; set; }

    public string VKodetarif { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtPaket IdPaketNavigation { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }
}