// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TR_ITEMOBATLANGSUNG")]
public partial class TrItemobatlangsung
{
    [Key]
    [Column("ID_ITEMOBATLANGSUNG", TypeName = "numeric(18, 0)")]
    public decimal IdItemobatlangsung { get; set; }

    [Column("V_NOKUITANSI")]
    [StringLength(10)]
    [Unicode(false)]
    public string VNokuitansi { get; set; }

    [Column("V_KDOBAT")]
    [StringLength(10)]
    [Unicode(false)]
    public string VKdobat { get; set; }

    [Column("ID_BARANG", TypeName = "numeric(18, 0)")]
    public decimal? IdBarang { get; set; }

    [Column("V_NOITEM")]
    [StringLength(6)]
    [Unicode(false)]
    public string VNoitem { get; set; }

    [Column("V_NMOBAT")]
    [StringLength(100)]
    [Unicode(false)]
    public string VNmobat { get; set; }

    [Column("D_HARGA", TypeName = "decimal(18, 0)")]
    public decimal? DHarga { get; set; }

    [Column("D_JUMLAH", TypeName = "decimal(18, 0)")]
    public decimal? DJumlah { get; set; }

    [Column("D_DISKON", TypeName = "decimal(18, 0)")]
    public decimal? DDiskon { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("C_APPROVE")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApprove { get; set; }

    [Column("D_APPROVE", TypeName = "datetime")]
    public DateTime? DApprove { get; set; }

    [Column("V_APPROVE")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApprove { get; set; }

    [Column("C_APPROVE_VER")]
    [StringLength(1)]
    [Unicode(false)]
    public string CApproveVer { get; set; }

    [Column("D_APPROVE_VER", TypeName = "datetime")]
    public DateTime? DApproveVer { get; set; }

    [Column("V_NOTEOBAT")]
    [StringLength(50)]
    [Unicode(false)]
    public string VNoteobat { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [Column("V_APPROVE_VER")]
    [StringLength(50)]
    [Unicode(false)]
    public string VApproveVer { get; set; }

    [ForeignKey("IdStatus")]
    [InverseProperty("TrItemobatlangsungs")]
    public virtual TmStatus IdStatusNavigation { get; set; }

    [ForeignKey("VNokuitansi")]
    [InverseProperty("TrItemobatlangsungs")]
    public virtual TtObatlangsung VNokuitansiNavigation { get; set; }
}