// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrJadwaldokter
{
    public long IdJadwal { get; set; }

    public string VKddokter { get; set; }

    public string VHari { get; set; }

    public string VJamstart { get; set; }

    public string VJamfinish { get; set; }

    public string VKoderuangan { get; set; }

    public string VNamaklinik { get; set; }

    public int? IServistime { get; set; }

    public bool? IsAktif { get; set; }

    public string VBy { get; set; }
}