// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TR_JADWALDOKTER")]
public partial class TrJadwaldokter
{
    [Key]
    [Column("ID_JADWAL")]
    public long IdJadwal { get; set; }

    [Column("V_KDDOKTER")]
    [StringLength(100)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("V_HARI")]
    [StringLength(30)]
    [Unicode(false)]
    public string VHari { get; set; }

    [Column("V_JAMSTART")]
    [StringLength(5)]
    [Unicode(false)]
    public string VJamstart { get; set; }

    [Column("V_JAMFINISH")]
    [StringLength(5)]
    [Unicode(false)]
    public string VJamfinish { get; set; }

    [Column("V_KODERUANGAN")]
    [StringLength(5)]
    [Unicode(false)]
    public string VKoderuangan { get; set; }

    [Column("V_NAMAKLINIK")]
    [StringLength(5)]
    [Unicode(false)]
    public string VNamaklinik { get; set; }

    [Column("I_SERVISTIME")]
    public int? IServistime { get; set; }

    [Column("IS_AKTIF")]
    public bool? IsAktif { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }
}