// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrPermintaandetail
{
    public decimal Permintaandetailid { get; set; }

    public decimal? Permintaanid { get; set; }

    public decimal? Barangid { get; set; }

    public decimal? Jumlah { get; set; }

    public decimal? Jumlahminta { get; set; }

    public string Status { get; set; }

    public decimal? Jumlahpesan { get; set; }

    public bool? Ispesan { get; set; }

    public decimal? Hargaavg { get; set; }

    public decimal? Discavg { get; set; }

    public decimal? Subtotalavg { get; set; }

    public string Inputby { get; set; }

    public DateTime? DTglinput { get; set; }

    public string VApproveCc { get; set; }

    public DateTime? DTglCc { get; set; }

    public string VApproveKeu { get; set; }

    public DateTime? DTglKeu { get; set; }

    public string VApprovePem { get; set; }

    public DateTime? DTglPem { get; set; }

    public int? IdStatus { get; set; }
}