// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrPemeriksaanpenunjang
{
    public decimal Idnum { get; set; }

    public string IdPasienpenunjang { get; set; }

    public decimal? IdMasterpemeriksaanpenunjang { get; set; }

    public string VKdpemeriksaan { get; set; }

    public string VNmpemeriksaan { get; set; }

    public string VHasil { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public string VPenunjang { get; set; }

    public string VBy { get; set; }

    public decimal? DDiskon { get; set; }

    public string CApprove { get; set; }

    public string VApprove { get; set; }

    public DateTime? DApprove { get; set; }
}