// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrPemesanandetail
{
    public decimal Pemesanandetailid { get; set; }

    public decimal? Barangid { get; set; }

    public decimal? Pemesananid { get; set; }

    public decimal? Jumlah { get; set; }

    public decimal? Harga { get; set; }

    public decimal? Discountnominal { get; set; }

    public decimal? Subtotal { get; set; }

    public decimal? Permintaandetailid { get; set; }

    public int? IdStatus { get; set; }
}