// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrPembayarandetail
{
    public decimal Pembayarandetailid { get; set; }

    public decimal? Pembayaranid { get; set; }

    public decimal? Penerimaanid { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Total { get; set; }
}