// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TrPelunasandetail
{
    public decimal Pelunasandetailid { get; set; }

    public decimal? Pelunasanid { get; set; }

    public decimal? Pembayaranid { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Total { get; set; }
}