// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtDiagnosarekap
{
    public decimal IdDiagnosarekap { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTgl { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VLain { get; set; }

    public string VKodetarif { get; set; }

    public DateTime? DTglrm { get; set; }

    public string VKdmasuk { get; set; }

    public string VNmmasuk { get; set; }

    public string VKdutama { get; set; }

    public string VNmutama { get; set; }

    public string VKdkomplikasi { get; set; }

    public string VNmkomplikasi { get; set; }

    public string VKdsekunder { get; set; }

    public string VNmsekunder { get; set; }

    public string VKdoperasi { get; set; }

    public string VNmoperasi { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }
}