// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtDiagnosa
{
    public decimal IdDiagnosa { get; set; }

    public string VNomordiagnosa { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTgldiagnosa { get; set; }

    public string VKodetarif { get; set; }

    public string VNote { get; set; }

    public string VBy { get; set; }

    public virtual ICollection<TtDiagnosaDetail> TtDiagnosaDetails { get; set; } = new List<TtDiagnosaDetail>();
}