// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtDiagnosaDetail
{
    public decimal IdDiagnosadetail { get; set; }

    public string VNomordiagnosa { get; set; }

    public string IdRegistrasi { get; set; }

    public string VKddiagnosa { get; set; }

    public string VNmdiagnosa { get; set; }

    public string VJenisdiagnosa { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VLain { get; set; }

    public DateTime? DTgl { get; set; }

    public string VKodetarif { get; set; }

    public string VNote { get; set; }

    public string VBy { get; set; }

    public int? IdStatus { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TtDiagnosa VNomordiagnosaNavigation { get; set; }
}