// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TT_HASILPEMERIKSAANPDS")]
public partial class TtHasilpemeriksaanpd
{
    [Key]
    [Column("ID_ANAMNESIS", TypeName = "numeric(18, 0)")]
    public decimal IdAnamnesis { get; set; }

    [Required]
    [Column("ID_REGISTRASI")]
    [StringLength(12)]
    [Unicode(false)]
    public string IdRegistrasi { get; set; }

    [Column("V_ANAMNESIS")]
    [Unicode(false)]
    public string VAnamnesis { get; set; }

    [Column("V_PMRKSNFISIK")]
    [Unicode(false)]
    public string VPmrksnfisik { get; set; }

    [Column("V_PMRKSNLANJUTAN")]
    [Unicode(false)]
    public string VPmrksnlanjutan { get; set; }

    [Column("V_PMRKSNPENUNJANG")]
    [Unicode(false)]
    public string VPmrksnpenunjang { get; set; }

    [Column("V_KDDOKTER")]
    [StringLength(6)]
    [Unicode(false)]
    public string VKddokter { get; set; }

    [Column("D_BERAT")]
    [StringLength(50)]
    [Unicode(false)]
    public string DBerat { get; set; }

    [Column("D_TINGGI")]
    [StringLength(50)]
    [Unicode(false)]
    public string DTinggi { get; set; }

    [Column("D_TENSI")]
    [StringLength(50)]
    [Unicode(false)]
    public string DTensi { get; set; }

    [Column("D_TENSI2")]
    [StringLength(50)]
    [Unicode(false)]
    public string DTensi2 { get; set; }

    [Column("D_NADI")]
    [StringLength(50)]
    [Unicode(false)]
    public string DNadi { get; set; }

    [Column("D_RR")]
    [StringLength(50)]
    [Unicode(false)]
    public string DRr { get; set; }

    [Column("D_SUHU")]
    [StringLength(50)]
    [Unicode(false)]
    public string DSuhu { get; set; }

    [Column("V_BY")]
    [StringLength(50)]
    [Unicode(false)]
    public string VBy { get; set; }

    [Column("D_TGL", TypeName = "datetime")]
    public DateTime? DTgl { get; set; }
}