// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtHasilpemeriksaanpd
{
    public decimal IdAnamnesis { get; set; }

    public string IdRegistrasi { get; set; }

    public string VAnamnesis { get; set; }

    public string VPmrksnfisik { get; set; }

    public string VPmrksnlanjutan { get; set; }

    public string VPmrksnpenunjang { get; set; }

    public string VKddokter { get; set; }

    public string DBerat { get; set; }

    public string DTinggi { get; set; }

    public string DTensi { get; set; }

    public string DTensi2 { get; set; }

    public string DNadi { get; set; }

    public string DRr { get; set; }

    public string DSuhu { get; set; }

    public string VBy { get; set; }

    public DateTime? DTgl { get; set; }
}