// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtHistoryStok
{
    public decimal IdHistory { get; set; }

    public string IdTransaksi { get; set; }

    public string IdKuitansi { get; set; }

    public DateTime? DTgltransaksi { get; set; }

    public string VKodetarif { get; set; }

    public string VLayanan { get; set; }

    public decimal? IdBarang { get; set; }

    public decimal? DMasuk { get; set; }

    public decimal? DKeluar { get; set; }

    public decimal? DHargabeli { get; set; }

    public decimal? DHargajual { get; set; }

    public string VKeterangan { get; set; }

    public DateTime? DLastupdate { get; set; }

    public string VBy { get; set; }

    public virtual TmGudang VKodetarifNavigation { get; set; }
}