// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtKuitansiudd
{
    public decimal IdKuitansiudd { get; set; }

    public string IdRegistrasi { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public DateTime? DTgl { get; set; }

    public string VKodetarif { get; set; }

    public string VKoderuangan { get; set; }

    public string VNorequest { get; set; }

    public bool? CStatus { get; set; }

    public string VBy { get; set; }

    public string VKoderequestobat { get; set; }

    public virtual ICollection<TtResepudd> TtResepudds { get; set; } = new List<TtResepudd>();

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}