// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtKuitansiresep
{
    public decimal Idn { get; set; }

    public string IdKuitansiresep { get; set; }

    public string IdRegistrasi { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public DateTime? DTgl { get; set; }

    public string VKodetarif { get; set; }

    public string VKoderuangan { get; set; }

    public string VNoresep { get; set; }

    public string VTiperesep { get; set; }

    public string VStatus { get; set; }

    public string Statusnotif { get; set; }

    public string VKoderequestobat { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveAa { get; set; }

    public string CApproveAa { get; set; }

    public DateTime? DApproveAa { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public int? IdStatus { get; set; }

    public string TtdDokter { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TmGudang VKoderequestobatNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}