// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtKunjungan
{
    public decimal IdNumkunjungan { get; set; }

    public string IdRegistrasi { get; set; }

    public string IdPasien { get; set; }

    public DateTime? DTglkunjungan { get; set; }

    public string VJamkunjungan { get; set; }

    public DateTime? DTglpulang { get; set; }

    public string VTujuankunjungan { get; set; }

    public string CIsbatal { get; set; }

    public string VAlasanbatal { get; set; }

    public decimal Rekananid { get; set; }

    public string VBy { get; set; }

    public string VKet { get; set; }

    public string VOtorisasi { get; set; }

    public DateTime? DTglotorisasi { get; set; }

    public int? IdStatus { get; set; }

    public decimal? VTransaksi { get; set; }

    public string VUmur { get; set; }

    public bool? IsCob { get; set; }

    public string VNomorsep { get; set; }

    public virtual TmPasien IdPasienNavigation { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }

    public virtual TmRekanan Rekanan { get; set; }

    public virtual ICollection<TtDiagnosarekap> TtDiagnosarekaps { get; set; } = new List<TtDiagnosarekap>();

    public virtual ICollection<TtPaket> TtPakets { get; set; } = new List<TtPaket>();

    public virtual ICollection<TtPasienpd> TtPasienpds { get; set; } = new List<TtPasienpd>();

    public virtual ICollection<TtPasienugd> TtPasienugds { get; set; } = new List<TtPasienugd>();

    public virtual ICollection<TtTindakan> TtTindakans { get; set; } = new List<TtTindakan>();
}