// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtKuitansiretur
{
    public decimal IdRetur { get; set; }

    public string VNomorretur { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTglretur { get; set; }

    public string VKodetarif { get; set; }

    public string VBy { get; set; }

    public string VApprove { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public int? IdStatus { get; set; }

    public virtual ICollection<TtRetur> TtReturs { get; set; } = new List<TtRetur>();
}