// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPaketPbReturDetail
{
    public decimal IdPaketpbReturdetail { get; set; }

    public decimal? IdPaketpbRetur { get; set; }

    public decimal? IdBarang { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DJmlpakai { get; set; }

    public decimal? DSisa { get; set; }

    public decimal? DHargajual { get; set; }

    public string VBy { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtPaketPbRetur IdPaketpbReturNavigation { get; set; }
}