// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPasienugd
{
    public decimal IdNumpasienugd { get; set; }

    public string IdRegistrasi { get; set; }

    public string IdPasienigd { get; set; }

    public DateTime DTgldatang { get; set; }

    public string VJamdatang { get; set; }

    public string VDibawaoleh { get; set; }

    public DateTime? DTglpulang { get; set; }

    public string VJampulang { get; set; }

    public string VCarakeluar { get; set; }

    public bool? BKasuspolisi { get; set; }

    public bool? BKasuskecelakaan { get; set; }

    public bool? BVisum { get; set; }

    public DateTime? DTglkelakaan { get; set; }

    public string VTmpkecelakaan { get; set; }

    public bool? BDiberitahukankekeluarga { get; set; }

    public bool? BDiberitahukankepolisi { get; set; }

    public string VKeadaanterakhir { get; set; }

    public DateTime? DTglpemberitahuan { get; set; }

    public string VJampemberitahuan { get; set; }

    public string VNmpemberitahu { get; set; }

    public string VPenjamin { get; set; }

    public string VRiwayatsingkat { get; set; }

    public bool? BPendarahan { get; set; }

    public string CSuhutubuh { get; set; }

    public string CNadi { get; set; }

    public string CTekanandarah { get; set; }

    public string VAnamnese { get; set; }

    public string VPemeriksaanfisik { get; set; }

    public string VPemeriksaanlanjutan { get; set; }

    public string VPemeriksaanpenunjang { get; set; }

    public string VBy { get; set; }

    public string CIsdone { get; set; }

    public string VKdpengirim { get; set; }

    public string VNmpengirim { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VKoderuangan { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TmAsal VKdpengirimNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}