// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPaketPbPakaiDetail
{
    public decimal IdPaketpbPakaidetail { get; set; }

    public decimal? IdPaketpbPakai { get; set; }

    public decimal? IdBarang { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DJmlpakai { get; set; }

    public decimal? DHargajual { get; set; }

    public string VBy { get; set; }

    public int? IdStatus { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public virtual TtPaketPbPakai IdPaketpbPakaiNavigation { get; set; }
}