// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPaketPbRetur
{
    public decimal IdPaketpbRetur { get; set; }

    public DateTime? DTglretur { get; set; }

    public decimal IdPaketpbPakai { get; set; }

    public decimal? IdPaketpb { get; set; }

    public string VKodetarif { get; set; }

    public string VKodetarifgdg { get; set; }

    public string IdRegistrasi { get; set; }

    public decimal? IdRekanan { get; set; }

    public string VBy { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtPaketPb IdPaketpbNavigation { get; set; }

    public virtual TtPaketPbPakai IdPaketpbPakaiNavigation { get; set; }

    public virtual TmRekanan IdRekananNavigation { get; set; }

    public virtual ICollection<TtPaketPbReturDetail> TtPaketPbReturDetails { get; set; } = new List<TtPaketPbReturDetail>();

    public virtual TmGudang VKodetarifNavigation { get; set; }

    public virtual TmGudang VKodetarifgdgNavigation { get; set; }
}