// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPasienpd
{
    public decimal IdNumpasienpds { get; set; }

    public string IdRegistrasi { get; set; }

    public string VKdpengirim { get; set; }

    public string VNmpengirim { get; set; }

    public string VKddokter { get; set; }

    public DateTime DTgldatang { get; set; }

    public int? IUrut { get; set; }

    public string VJam { get; set; }

    public decimal? IdJadwal { get; set; }

    public string CIsdone { get; set; }

    public string VBy { get; set; }

    public string IdPasienpds { get; set; }

    public string VStatus { get; set; }

    public string VKoderuangan { get; set; }

    public int? IdStatus { get; set; }

    public bool? IdVoucher { get; set; }

    public virtual TmJadwaldokter IdJadwalNavigation { get; set; }

    public virtual TtKunjungan IdRegistrasiNavigation { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }

    public virtual TmDokter VKddokterNavigation { get; set; }

    public virtual TmAsal VKdpengirimNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}