// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPasienpenunjang
{
    public decimal IdNumpasienpenj { get; set; }

    public string IdRegistrasi { get; set; }

    public string IdPasien { get; set; }

    public DateTime? DTglkunjungan { get; set; }

    public string VJam { get; set; }

    public int? IUrut { get; set; }

    public string VNote { get; set; }

    public string CIsdone { get; set; }

    public string VPenunjang { get; set; }

    public string VKoderuangan { get; set; }

    public string VBy { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VKdunit { get; set; }

    public string VUnit { get; set; }

    public string VKdpengirim { get; set; }

    public string VNmpengirim { get; set; }

    public string IdPasienpenunjang { get; set; }

    public string VStatus { get; set; }

    public string VKelas { get; set; }

    public int? IdStatus { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }

    public virtual TmRuang VKoderuanganNavigation { get; set; }
}