// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPaketPbApp
{
    public decimal IdPaketpbApp { get; set; }

    public DateTime? DTglapp { get; set; }

    public decimal? IdPaketpb { get; set; }

    public string VKodetarif { get; set; }

    public string VKodetarifgdg { get; set; }

    public string VByapp { get; set; }

    public int? IdStatus { get; set; }

    public virtual TtPaketPb IdPaketpbNavigation { get; set; }

    public virtual ICollection<TtPaketPbAppDetail> TtPaketPbAppDetails { get; set; } = new List<TtPaketPbAppDetail>();

    public virtual TmGudang VKodetarifNavigation { get; set; }

    public virtual TmGudang VKodetarifgdgNavigation { get; set; }
}