// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPembayaran
{
    public decimal Idpembayaran { get; set; }

    public string VNomorbyrpasien { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime DTgl { get; set; }

    public decimal? DJumlah { get; set; }

    public string VBy { get; set; }
}