// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPembayaranDetail
{
    public decimal Idn { get; set; }

    public string VNomorbyrpasien { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTgl { get; set; }

    public decimal? DJumlah { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public decimal? DBeacharge { get; set; }

    public decimal? DAdministrasi { get; set; }

    public decimal? DMaterai { get; set; }

    public decimal? DDeposit { get; set; }

    public decimal? DBayarkredit { get; set; }

    public decimal? DChargekredit { get; set; }

    public string VNonamacc { get; set; }

    public decimal? DBayartunai { get; set; }

    public decimal? DPerjanjianprshn { get; set; }

    public decimal? DAsuransi { get; set; }

    public decimal? DLainlain { get; set; }

    public decimal? DKembali { get; set; }

    public decimal? DCompliment { get; set; }

    public string VKreditnamabank { get; set; }

    public string VKreditnobatch { get; set; }

    public string VKreditnocard { get; set; }

    public string VKreditjeniscard { get; set; }

    public decimal? DBayartransfer { get; set; }

    public string VTransfernorekasal { get; set; }

    public string VTransfernomor { get; set; }

    public string VTransfernamabank { get; set; }

    public string VBy { get; set; }

    public string CStatus { get; set; }

    public string VOtorisasi { get; set; }

    public int? IdStatus { get; set; }

    public virtual TmStatus IdStatusNavigation { get; set; }
}