// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtPemeriksaanpa
{
    public string IdPasienlab { get; set; }

    public string VBahan { get; set; }

    public string VKdpemeriksaanlab { get; set; }

    public string VNmpemeriksaan { get; set; }

    public string VRingkasan { get; set; }

    public string VDiagnosa { get; set; }

    public string VPeriksakemarin { get; set; }

    public DateTime? DTglterima { get; set; }

    public DateTime? DTgljawaban { get; set; }

    public string VMakro { get; set; }

    public string VMikro { get; set; }

    public string VKesimpulan { get; set; }

    public string VSaran { get; set; }

    public string VCatatan { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public string VBy { get; set; }

    public virtual TmDokter VKddokterNavigation { get; set; }
}