// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtReturApp
{
    public decimal IdReturapp { get; set; }

    public DateTime? DTglapp { get; set; }

    public string VKodetarif { get; set; }

    public string VBy { get; set; }

    public int? IdStatus { get; set; }

    public virtual ICollection<TtReturAppDetail> TtReturAppDetails { get; set; } = new List<TtReturAppDetail>();

    public virtual TmGudang VKodetarifNavigation { get; set; }
}