// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtReturDist
{
    public decimal IdReturdist { get; set; }

    public DateTime? DTgldist { get; set; }

    public string VKodetarif { get; set; }

    public string VBy { get; set; }

    public int? IdStatus { get; set; }

    public virtual ICollection<TtReturDistDetail> TtReturDistDetails { get; set; } = new List<TtReturDistDetail>();

    public virtual TmGudang VKodetarifNavigation { get; set; }
}