// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtResepudd
{
    public decimal IdResepudd { get; set; }

    public decimal? IdKuitansiudd { get; set; }

    public decimal? IdBarang { get; set; }

    public string VKdobat { get; set; }

    public string VNmobat { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DHarga { get; set; }

    public string CTipeaskes { get; set; }

    public bool? CStatus { get; set; }

    public string VNote { get; set; }

    public string VBy { get; set; }

    public string VApprove { get; set; }

    public virtual TtKuitansiudd IdKuitansiuddNavigation { get; set; }
}