// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtResep
{
    public decimal IdObatresep { get; set; }

    public string IdResep { get; set; }

    public string IdKuitansiresep { get; set; }

    public decimal? IdBarang { get; set; }

    public string VKdobat { get; set; }

    public string VNmobat { get; set; }

    public string VNmracikan { get; set; }

    public string DDosisracikan { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DJmlracikan { get; set; }

    public decimal? DHarga { get; set; }

    public decimal? DJmltebus { get; set; }

    public string VNoteobat { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? Rekananid { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApproveAa { get; set; }

    public string CApproveAa { get; set; }

    public DateTime? DApproveAa { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }

    public int? IdStatus { get; set; }
}