// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtReturalke
{
    public decimal IdReturalkes { get; set; }

    public string IdRegistrasi { get; set; }

    public decimal IdAlkes { get; set; }

    public decimal? IdBarang { get; set; }

    public string VKdobat { get; set; }

    public string VNmobat { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DHarga { get; set; }

    public string CTipeaskes { get; set; }

    public string CApprove { get; set; }

    public string VApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public DateTime? DTglretur { get; set; }

    public string VBy { get; set; }

    public string VNote { get; set; }

    public string VSettingretur { get; set; }

    public string VApproveVer { get; set; }

    public string CApproveVer { get; set; }

    public DateTime? DApproveVer { get; set; }
}