// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Wincare.Pelayanan.Migration.Models;

[Table("TT_RETURSUPPLIER")]
public partial class TtRetursupplier
{
    [Key]
    [Column("RETURID", TypeName = "numeric(18, 0)")]
    public decimal Returid { get; set; }

    [Column("PENERIMAANID", TypeName = "numeric(18, 0)")]
    public decimal? Penerimaanid { get; set; }

    [Column("NOMOR")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nomor { get; set; }

    [Column("TANGGAL", TypeName = "datetime")]
    public DateTime? Tanggal { get; set; }

    [Column("KODERUANG")]
    [StringLength(5)]
    [Unicode(false)]
    public string Koderuang { get; set; }

    [Column("INPUTBY")]
    [StringLength(50)]
    [Unicode(false)]
    public string Inputby { get; set; }

    [Column("NOTE")]
    [StringLength(500)]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("STATUS")]
    [StringLength(1)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("ID_STATUS")]
    public int? IdStatus { get; set; }

    [InverseProperty("Retur")]
    public virtual ICollection<TrReturdetail> TrReturdetails { get; set; } = new List<TrReturdetail>();
}