// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtReturAppDetail
{
    public decimal IdReturappdetail { get; set; }

    public decimal? IdReturapp { get; set; }

    public string IdReturdetail { get; set; }

    public string IdResep { get; set; }

    public DateTime? DTglretur { get; set; }

    public decimal? IdBarang { get; set; }

    public string VNmobat { get; set; }

    public decimal? DJml { get; set; }

    public decimal? DHarga { get; set; }

    public string VBy { get; set; }

    public string IdPasien { get; set; }

    public string VNamapasien { get; set; }

    public string VTujuankunjungan { get; set; }

    public string VRuangan { get; set; }

    public string IdStatus { get; set; }

    public virtual TtReturApp IdReturappNavigation { get; set; }
}