// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtResepTulisracikan
{
    public decimal Idn { get; set; }

    public string VNoresep { get; set; }

    public string IdRegistrasi { get; set; }

    public DateTime? DTgl { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public decimal? Rekananid { get; set; }

    public string VKoderuangan { get; set; }

    public string VKoderequestobat { get; set; }

    public string VKodetarif { get; set; }

    public string NotePerawat { get; set; }

    public string NoteFarmasi { get; set; }

    public string VBy { get; set; }

    public string VStatus { get; set; }

    public string VApprove { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string TtdDokter { get; set; }

    public int? IdStatus { get; set; }
}