// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Wincare.Pelayanan.Migration.Models;

public partial class TtTindakanDetail
{
    public decimal IdTindakandetail { get; set; }

    public string VNomortindakan { get; set; }

    public string IdRegistrasi { get; set; }

    public string VKdtindakan { get; set; }

    public string VNmtindakan { get; set; }

    public int? IJml { get; set; }

    public decimal? DBiaya { get; set; }

    public decimal? DCito { get; set; }

    public decimal? DPenyulit { get; set; }

    public decimal? D2tnd { get; set; }

    public decimal? DAdm { get; set; }

    public decimal? DDiskon { get; set; }

    public decimal? DSubtotal { get; set; }

    public decimal? DBeapasien { get; set; }

    public decimal? DBearekanan { get; set; }

    public string VKddokter { get; set; }

    public string VNmdokter { get; set; }

    public DateTime? DTgltindakan { get; set; }

    public string VNote { get; set; }

    public string VKodetarif { get; set; }

    public decimal? DJasamedis { get; set; }

    public decimal? DJasamedis2 { get; set; }

    public decimal? DJasamedis3 { get; set; }

    public decimal? DJasars { get; set; }

    public decimal? DBahanalkes { get; set; }

    public string VGroup { get; set; }

    public string VKddokter2 { get; set; }

    public string VNmdokter2 { get; set; }

    public string VKddokter3 { get; set; }

    public string VNmdokter3 { get; set; }

    public string VBy { get; set; }

    public string CApprove { get; set; }

    public DateTime? DApprove { get; set; }

    public string VApprove { get; set; }

    public string CApprove2 { get; set; }

    public DateTime? DApprove2 { get; set; }

    public string VStatus { get; set; }

    public int? IdStatus { get; set; }

    public string VApprove2 { get; set; }
}